project:
  type: book
  output-dir: docs

book:
  title: "Foundations of Data Science"
  subtitle: "Beyond the Numbers"
  author: "Oliver Schabenberger"
  date: "January 13, 2025"
  reader-mode: true

  page-footer:
    left: |
      Foundations of Data Science by Oliver Schabenberger
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: FoundationsCover.png

  chapters:
    - index.qmd
    - intro.qmd

    - part: "Module I. Data Science Projects"
      chapters:
        - proj/history.qmd
        - proj/lifecycle.qmd
        - proj/thinkingds.qmd
        - proj/teams.qmd

    - part: "Module II. Business Understanding: Discovery"
      chapters:
        - busi/bus_intro.qmd
        - busi/approach.qmd
        - busi/examples.qmd
        
    - part: "Module III. Data Engineering"
      chapters:
        - data/data_intro.qmd
        - data/sources_and_files.qmd
        - data/data_access.qmd
        - data/quality.qmd
        - data/summarization.qmd
        - data/visualization.qmd
        - data/sqlbasics.qmd
        - data/integration.qmd

    - part: "Module IV. Modeling"
      chapters:
        - statlearning/general.qmd
        - statlearning/featproc.qmd

    - part: "Module V. Evaluation & Communication"

    - part: "Module VI. Operationalization"
      chapters:
        - integ/ds_softwareeng.qmd
        - integ/coding_practices.qmd
        - integ/tools.qmd

    - part: "Module VII. Applied Ethics in Data Science"
      chapters:
        - ethics/intro.qmd
        - ethics/gonewrong.qmd
        - ethics/bias_harm.qmd
        - ethics/privacy.qmd
        - ethics/genAI.qmd

    - part: "Module VIII. Review Topics"
      chapters:
        - statlearning/mathstat.qmd
        - statlearning/linalg.qmd

    - references.qmd

bibliography: references.bib
# csl: apa.csl

format:
  html:
    theme:
        light: [cosmo,customstyle.scss]
        dark: [slate,customstyle.scss]
#   embed-resources: true
    smooth-scroll: true
    number-sections: true
    number-depth: 2
    toc-depth: 4
    toc-expand: 2
    pdf:
    documentclass: scrreprt
#    include-in-header: latexmacros.tex

# editor: visual
