project:
  type: book
  output-dir: docs

book:
  title: "Foundations of Data Science"
  subtitle: "Beyond the Numbers"
  author: "Oliver Schabenberger"
  date: "03/26/2025"
  reader-mode: true

  page-footer:
    left: |
      Foundations of Data Science by Oliver Schabenberger
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: FoundationsCover.png

  chapters:
    - index.qmd
    - intro.qmd

    - part: "Module I. Understanding Data Science"
      chapters:
        - proj/history.qmd
        - proj/lifecycle.qmd
        - proj/teams.qmd
        - proj/thinkingds.qmd

    - part: "Module II. Business Understanding: Discovery"
      chapters:
        - busi/bus_intro.qmd
        - busi/approach.qmd
        - busi/examples.qmd
        
    - part: "Module III. Data Engineering"
      chapters:
        - data/data_intro.qmd
        - data/sources_and_files.qmd
        - data/data_access.qmd
        - data/quality.qmd
        - data/summarization.qmd
        - data/visualization.qmd
        - data/sqlbasics.qmd
        - data/integration.qmd

    - part: "Module IV. Modeling Data"
      chapters:
        - models/model_intro.qmd
        - models/model_concepts.qmd
        - models/correlation.qmd
        - models/bias_variance.qmd
        - models/test_cv.qmd
        - models/messydata.qmd
#        - statlearning/general.qmd
        - models/featproc.qmd

    - part: "Module V. Evaluation & Communication"

    - part: "Module VI. Operationalization"
      chapters:
        - integ/integ_intro.qmd
        - integ/offline_online.qmd
        - integ/interfaces.qmd
        - integ/orchestration.qmd
        - integ/lead_scoring.qmd
        - integ/test_experiment.qmd
        - integ/ds_softwareeng.qmd
        - integ/tools.qmd

    - part: "Module VII. Applied Ethics in Data Science"
      chapters:
        - ethics/intro.qmd
        - ethics/gonewrong.qmd
        - ethics/bias_harm.qmd
        - ethics/privacy.qmd
        - ethics/genAI.qmd

    - part: "Module VIII. Review Topics"
      chapters:
        - reviewmaterial/probability.qmd
        - reviewmaterial/statistics.qmd
        - reviewmaterial/linalg.qmd
        - reviewmaterial/estimation.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        light: [cosmo,customstyle.scss]
        dark: [slate,customstyle.scss]
    grid:
      sidebar-width: 250px
      body-width: 950px
      margin-width: 250px
      gutter-width: 1.5rem
    smooth-scroll: true
    number-sections: true
    number-depth: 2
    toc-depth: 4
    toc-expand: 2
    pdf:
    documentclass: scrreprt

