project:
  type: book
  output-dir: docs

book:
  title: "Foundations of Data Science"
  subtitle: "Beyond the Numbers"
  author: "Oliver Schabenberger"
  date: "08/09/2024"
  reader-mode: true

  page-footer:
    left: |
      Foundations of Data Science by Oliver Schabenberger
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: FoundationsCover.png

  chapters:
    - index.qmd
    - intro.qmd

    - part: "Part I. Data Science and Data Science Projects"
      chapters:
        - proj/history.qmd
        - proj/lifecycle.qmd

    - part: "Part II. Data Preparation and Understanding"
      chapters:
        - data/sources_and_files.qmd
        - data/data_access.qmd
        - data/quality.qmd
        - data/summarization.qmd
        - data/visualization.qmd
        - data/sqlbasics.qmd
        - data/integration.qmd

    - part: "Part III. Statistical Learning"
      chapters:
        - statlearning/general.qmd
        - statlearning/mathstat.qmd
        - statlearning/linalg.qmd
        - statlearning/featproc.qmd
        
    - part: "Part IV. Applied Ethics in Data Science"
      chapters:
        - ethics/intro.qmd
        - ethics/gonewrong.qmd
        - ethics/bias_harm.qmd
        - ethics/privacy.qmd

    - part: "Part V. Integration of Data Science Solutions"
      chapters:
        - integ/coding_practices.qmd
        - integ/tools.qmd
        
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        light: [cosmo,customstyle.scss]
        dark: [slate,customstyle.scss]
#   embed-resources: true
    smooth-scroll: true
    number-sections: true
    number-depth: 2
    toc-depth: 4
    toc-expand: 2
    pdf:
    documentclass: scrreprt
#    include-in-header: latexmacros.tex

# editor: visual
