project:
  type: book

book:
  title: "Foundations of Data Science"
  subtitle: "Beyond the Numbers"
  author: "Oliver Schabenberger"
  date: "06/05/2024"
  reader-mode: true

  page-footer:
    left: |
      Foundations of Data Science by Oliver Schabenberger
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: FoundationsCover.png

  chapters:
    - index.qmd
    - intro.qmd

    - part: proj.qmd
      chapters:
        - proj/history.qmd
        - proj/lifecycle.qmd

    - part: databasics.qmd
      chapters:
        - data/sources_and_files.qmd
        - data/data_access.qmd
        - data/quality.qmd
        - data/summarization.qmd
        - data/visualization.qmd
        - data/sqlbasics.qmd
        - data/integration.qmd

    - part: stat_learning.qmd
      chapters:
        - statlearning/general.qmd
        - statlearning/mathstat.qmd
        - statlearning/linalg.qmd
        - statlearning/featproc.qmd
        
    - part: "Applied Ethics in Data Science"
      chapters:
        - ethics/intro.qmd
        - ethics/bias_harm.qmd
        - ethics/privacy.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        light: [cosmo,customstyle.scss]
        dark: [slate,customstyle.scss]
#   embed-resources: true
    smooth-scroll: true
    number-sections: true
    number-depth: 2
    toc-depth: 4
    toc-expand: 2
    pdf:
    documentclass: scrreprt
#    include-in-header: latexmacros.tex

# editor: visual
