<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Foundations of Data Science - 12&nbsp; Data Quality</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../data/summarization.html" rel="next">
<link href="../data/data_access.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<script src="https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js" crossorigin="anonymous"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../data/data_intro.html">Module III. Data Engineering</a></li><li class="breadcrumb-item"><a href="../data/quality.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data Quality</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Foundations of Data Science</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Module I. Understanding Data Science</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../proj/history.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">History and Evolution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../proj/lifecycle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Project Lifecycle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../proj/teams.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Science Teams</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../proj/thinkingds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Thinking Like a Data Scientist</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Module II. Business Understanding: Discovery</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../busi/bus_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../busi/approach.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Approach and Methodology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../busi/examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Example: Email Campaign Optimization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Module III. Data Engineering</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/data_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/sources_and_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Sources and File Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/data_access.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data Access</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/quality.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data Quality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/summarization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Data Summarization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/sqlbasics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">SQL Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Data Integration</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Module IV. Modeling Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../models/model_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../models/model_concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">General Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../models/correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Correlation and Causation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../models/bias_variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">The Bias-Variance Tradeoff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../models/test_cv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Testing, Validation, Cross-Validation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../models/messydata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Messy Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../models/featproc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Feature and Target Processing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Module V. Evaluation &amp; Communication</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Module VI. Operationalization</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/integ_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/offline_online.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Offline and Online Deployments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/interfaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Software Interfaces</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/orchestration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Orchestration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/lead_scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Lead Scoring Tutorial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/test_experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Testing and Experimentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/ds_softwareeng.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Data Science Software Engineering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Data Science Tools</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Module VII. Applied Ethics in Data Science</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ethics/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ethics/gonewrong.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">How Things Go Wrong</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ethics/bias_harm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Bias and Harm in Algorithms</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ethics/privacy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Personal Information and Personal Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ethics/genAI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Ethics of Generative AI</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text">Module VIII. Review Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviewmaterial/probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviewmaterial/statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviewmaterial/linalg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Linear Algebra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reviewmaterial/estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-data-profiling" id="toc-sec-data-profiling" class="nav-link active" data-scroll-target="#sec-data-profiling"><span class="header-section-number">12.1</span> Data Profiling</a>
  <ul>
  <li><a href="#the-first-date-with-your-data" id="toc-the-first-date-with-your-data" class="nav-link" data-scroll-target="#the-first-date-with-your-data">The First Date with your Data</a></li>
  <li><a href="#california-housing-prices" id="toc-california-housing-prices" class="nav-link" data-scroll-target="#california-housing-prices">California Housing Prices</a></li>
  <li><a href="#profiling-tools" id="toc-profiling-tools" class="nav-link" data-scroll-target="#profiling-tools">Profiling Tools</a></li>
  </ul></li>
  <li><a href="#sec-missing-values" id="toc-sec-missing-values" class="nav-link" data-scroll-target="#sec-missing-values"><span class="header-section-number">12.2</span> Missing Values</a>
  <ul>
  <li><a href="#missing-value-process" id="toc-missing-value-process" class="nav-link" data-scroll-target="#missing-value-process">Missing Value Process</a></li>
  <li><a href="#missing-values-in-pandas" id="toc-missing-values-in-pandas" class="nav-link" data-scroll-target="#missing-values-in-pandas">Missing Values in Pandas</a></li>
  <li><a href="#working-with-missing-values-in-data-sets" id="toc-working-with-missing-values-in-data-sets" class="nav-link" data-scroll-target="#working-with-missing-values-in-data-sets">Working with Missing Values in Data Sets</a></li>
  <li><a href="#visualizing-missing-value-patterns" id="toc-visualizing-missing-value-patterns" class="nav-link" data-scroll-target="#visualizing-missing-value-patterns">Visualizing Missing Value Patterns</a></li>
  <li><a href="#data-imputation" id="toc-data-imputation" class="nav-link" data-scroll-target="#data-imputation">Data Imputation</a></li>
  </ul></li>
  <li><a href="#outlier-and-anomalies" id="toc-outlier-and-anomalies" class="nav-link" data-scroll-target="#outlier-and-anomalies"><span class="header-section-number">12.3</span> Outlier and Anomalies</a></li>
  <li><a href="#unbalanced-data" id="toc-unbalanced-data" class="nav-link" data-scroll-target="#unbalanced-data"><span class="header-section-number">12.4</span> Unbalanced Data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../data/data_intro.html">Module III. Data Engineering</a></li><li class="breadcrumb-item"><a href="../data/quality.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data Quality</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-data-quality" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data Quality</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-data-profiling" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="sec-data-profiling"><span class="header-section-number">12.1</span> Data Profiling</h2>
<section id="the-first-date-with-your-data" class="level3">
<h3 class="anchored" data-anchor-id="the-first-date-with-your-data">The First Date with your Data</h3>
<p>Data profiling is one of the first steps to take when you encounter a data set for the first time. It is how you kick-start the exploratory data analysis (EDA). <span class="citation" data-cites="Borne_2021_profiling">(<a href="../references.html#ref-Borne_2021_profiling" role="doc-biblioref">Borne 2021</a>)</span> refers to it as “having that first date with your data.” We are not looking to derive new insights from the data or to build amazing machine learning models at this stage; we want to create a high-level report of the data’s content and condition. We want to know what we are dealing with. Common questions and issues addressed during profiling are</p>
<ul>
<li><p>Which variables (attributes) are in the data?</p></li>
<li><p>How many rows and columns are there?</p></li>
<li><p>Which variables are quantitative (represent numbers), and which variables are qualitative (represent class memberships)</p></li>
<li><p>Are qualitative variables coded as strings, objects, numbers?</p></li>
<li><p>Are there complex data types such as JSON documents, images, audio, video encoded in the data?</p></li>
<li><p>What are the ranges (min, max) of the variables. Are these reasonable or do they suggest outliers or measurement errors?</p></li>
<li><p>What is the distribution of quantitative variables?</p></li>
<li><p>What is the mean, median, and standard deviation of quantitative variables?</p></li>
<li><p>What are the unique values of qualitative variables?</p></li>
<li><p>Do coded fields such as ZIP codes, account numbers, email addresses, state codes have the correct format?</p></li>
<li><p>Are there attributes that have only a single value?</p></li>
<li><p>Are there duplicate entries?</p></li>
<li><p>Are there missing values in one or more variables?</p></li>
<li><p>What are the strengths and direction of pairwise associations between the variables?</p></li>
<li><p>Are some attributes perfectly correlated, for example, birthdate and age or temperatures in degree Celsius and degree Fahrenheit.</p></li>
</ul>
</section>
<section id="california-housing-prices" class="level3">
<h3 class="anchored" data-anchor-id="california-housing-prices">California Housing Prices</h3>
<p>In this subsection we consider a data set on housing prices in California, based on the 1990 census and available on <a href="https://www.kaggle.com/datasets/camnugent/california-housing-prices">Kaggle</a>. The data contain information about geographic location, housing, and population within blocks. California has over 8,000 census tracts and a tract can have multiple block groups. There are over 20,000 census block groups and over 700,000 census blocks in California.</p>
<p>The variables in the data are:</p>
<table class="table-striped table">
<caption>Variables in the California Housing Prices data set.</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>longitude</td>
<td>A measure of how far west a house is; a higher value is farther west</td>
</tr>
<tr class="even">
<td>latitude</td>
<td>A measure of how far north a house is; a higher value is farther north</td>
</tr>
<tr class="odd">
<td>housing_median_age</td>
<td>Median age of a house within a block; a lower number is a newer building</td>
</tr>
<tr class="even">
<td>total_rooms</td>
<td>Total number of rooms within a block</td>
</tr>
<tr class="odd">
<td>total_bedrooms</td>
<td>Total number of bedrooms within a block</td>
</tr>
<tr class="even">
<td>population</td>
<td>Total number of people residing within a block</td>
</tr>
<tr class="odd">
<td>households</td>
<td>Total number of households, a group of people residing within a home unit, for a block</td>
</tr>
<tr class="even">
<td>median_income</td>
<td>Median income for households within a block of houses (measured in tens of thousands of US Dollars)</td>
</tr>
<tr class="odd">
<td>median_house_value</td>
<td>Median house value for households within a block (measured in US Dollars)</td>
</tr>
<tr class="even">
<td>ocean_proximity</td>
<td>Location of house with respect to ocean/sea</td>
</tr>
</tbody>
</table>
<p>The variable description is important metadata to understand the data. A variable such as <code>totalRooms</code> could be understood as the number of rooms in a building and the <code>medianHouseValue</code> could then mean the median of the houses that have that number of rooms. However, since the data are not for individual houses but blocks, <code>totalRooms</code> represents the sum of all the rooms in all the houses in that block.</p>
<p>We start data profiling a pandas DataFrame of the data with getting basic info and a listing of the first few observations.</p>
<div id="91b0c789" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>CA_houses <span class="op">=</span> pd.read_csv(<span class="st">"../datasets/CaliforniaHousing_1990.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>CA_houses.info()</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>CA_houses.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">longitude</th>
<th data-quarto-table-cell-role="th">latitude</th>
<th data-quarto-table-cell-role="th">housing_median_age</th>
<th data-quarto-table-cell-role="th">total_rooms</th>
<th data-quarto-table-cell-role="th">total_bedrooms</th>
<th data-quarto-table-cell-role="th">population</th>
<th data-quarto-table-cell-role="th">households</th>
<th data-quarto-table-cell-role="th">median_income</th>
<th data-quarto-table-cell-role="th">median_house_value</th>
<th data-quarto-table-cell-role="th">ocean_proximity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>-122.23</td>
<td>37.88</td>
<td>41.0</td>
<td>880.0</td>
<td>129.0</td>
<td>322.0</td>
<td>126.0</td>
<td>8.3252</td>
<td>452600.0</td>
<td>NEAR BAY</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-122.22</td>
<td>37.86</td>
<td>21.0</td>
<td>7099.0</td>
<td>1106.0</td>
<td>2401.0</td>
<td>1138.0</td>
<td>8.3014</td>
<td>358500.0</td>
<td>NEAR BAY</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-122.24</td>
<td>37.85</td>
<td>52.0</td>
<td>1467.0</td>
<td>190.0</td>
<td>496.0</td>
<td>177.0</td>
<td>7.2574</td>
<td>352100.0</td>
<td>NEAR BAY</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>-122.25</td>
<td>37.85</td>
<td>52.0</td>
<td>1274.0</td>
<td>235.0</td>
<td>558.0</td>
<td>219.0</td>
<td>5.6431</td>
<td>341300.0</td>
<td>NEAR BAY</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-122.25</td>
<td>37.85</td>
<td>52.0</td>
<td>1627.0</td>
<td>280.0</td>
<td>565.0</td>
<td>259.0</td>
<td>3.8462</td>
<td>342200.0</td>
<td>NEAR BAY</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>We can immediately answer several questions about the data:</p>
<ul>
<li><p>There are 20,640 rows and 10 columns</p></li>
<li><p>Except for <code>ocean_proximity</code>, which is of object type (string), all other variables are stored as 64-bit floats. Variables <code>total_rooms</code>, <code>total_bedrooms</code>, <code>population</code>, and <code>households</code> are naturally integers; since they appeared in the CSV file with a decimal point, they were assigned a floating point data type.</p></li>
<li><p>Only the <code>total_bedrooms</code> variable has missing values, 20,640 – 20,433 = 207 values for this variable are unobserved. This shows a high level of completeness of the data set. (More on missing values in the next section).</p></li>
<li><p>The listing of the first five observations confirms that variables are counts or sums at the block-level, rather than data for individual houses.</p></li>
<li><p>The <code>latitude</code> and <code>longitude</code> values differ in the second decimal place, suggesting that blocks (=rows of the data set) have unique geographic location, but we cannot be sure.</p></li>
<li><p>The <code>ocean_proximity</code> entries are in all caps. We want to see the other values in that column to make sure the entries are consistent. Knowing the format of strings is important for filtering (selecting) or grouping observations.</p></li>
</ul>
<p>The next step is to use pandas <code>describe()</code> function to compute basic summaries of the variables.</p>
<div id="aa4cb4ba" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>CA_houses.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">longitude</th>
<th data-quarto-table-cell-role="th">latitude</th>
<th data-quarto-table-cell-role="th">housing_median_age</th>
<th data-quarto-table-cell-role="th">total_rooms</th>
<th data-quarto-table-cell-role="th">total_bedrooms</th>
<th data-quarto-table-cell-role="th">population</th>
<th data-quarto-table-cell-role="th">households</th>
<th data-quarto-table-cell-role="th">median_income</th>
<th data-quarto-table-cell-role="th">median_house_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>20640.000000</td>
<td>20640.000000</td>
<td>20640.000000</td>
<td>20640.000000</td>
<td>20433.000000</td>
<td>20640.000000</td>
<td>20640.000000</td>
<td>20640.000000</td>
<td>20640.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>-119.569704</td>
<td>35.631861</td>
<td>28.639486</td>
<td>2635.763081</td>
<td>537.870553</td>
<td>1425.476744</td>
<td>499.539680</td>
<td>3.870671</td>
<td>206855.816909</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>2.003532</td>
<td>2.135952</td>
<td>12.585558</td>
<td>2181.615252</td>
<td>421.385070</td>
<td>1132.462122</td>
<td>382.329753</td>
<td>1.899822</td>
<td>115395.615874</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>-124.350000</td>
<td>32.540000</td>
<td>1.000000</td>
<td>2.000000</td>
<td>1.000000</td>
<td>3.000000</td>
<td>1.000000</td>
<td>0.499900</td>
<td>14999.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>-121.800000</td>
<td>33.930000</td>
<td>18.000000</td>
<td>1447.750000</td>
<td>296.000000</td>
<td>787.000000</td>
<td>280.000000</td>
<td>2.563400</td>
<td>119600.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>-118.490000</td>
<td>34.260000</td>
<td>29.000000</td>
<td>2127.000000</td>
<td>435.000000</td>
<td>1166.000000</td>
<td>409.000000</td>
<td>3.534800</td>
<td>179700.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>-118.010000</td>
<td>37.710000</td>
<td>37.000000</td>
<td>3148.000000</td>
<td>647.000000</td>
<td>1725.000000</td>
<td>605.000000</td>
<td>4.743250</td>
<td>264725.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>-114.310000</td>
<td>41.950000</td>
<td>52.000000</td>
<td>39320.000000</td>
<td>6445.000000</td>
<td>35682.000000</td>
<td>6082.000000</td>
<td>15.000100</td>
<td>500001.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>For each of the numeric variables, <code>describe()</code> computes the number of non-missing values (count), the sample mean (mean), the sample standard deviation (std), the minimum (min), maximum (max) and three percentiles (25%, 50%, 75%).</p>
<p>The results confirm that all variables have complete data (no missing values) except for <code>total_bedrooms</code>. The min and max values are useful to see the range (range = max – min) for the variables and to spot outliers and unusual values. It is suspicious that there is one or more blocks with a single household. This is not necessarily the same record that has 2 <code>total_rooms</code> and a population of 3.</p>
<div id="e21c01ff" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>CA_houses[CA_houses[<span class="st">"households"</span>] <span class="op">==</span> <span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">longitude</th>
<th data-quarto-table-cell-role="th">latitude</th>
<th data-quarto-table-cell-role="th">housing_median_age</th>
<th data-quarto-table-cell-role="th">total_rooms</th>
<th data-quarto-table-cell-role="th">total_bedrooms</th>
<th data-quarto-table-cell-role="th">population</th>
<th data-quarto-table-cell-role="th">households</th>
<th data-quarto-table-cell-role="th">median_income</th>
<th data-quarto-table-cell-role="th">median_house_value</th>
<th data-quarto-table-cell-role="th">ocean_proximity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">16171</td>
<td>-122.5</td>
<td>37.79</td>
<td>52.0</td>
<td>8.0</td>
<td>1.0</td>
<td>13.0</td>
<td>1.0</td>
<td>15.0001</td>
<td>500001.0</td>
<td>NEAR BAY</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>This is indeed a suspicious record. There is a single household in the block, but thirteen people are living in the block in a house with eight rooms and one bedroom. An unusual configuration that should be examined for possible data entry errors.</p>
</section>
<section id="profiling-tools" class="level3">
<h3 class="anchored" data-anchor-id="profiling-tools">Profiling Tools</h3>
<p>You can accelerate the data profiling task by using packages such as ydata_profiling (fka pandas_profiling), lux, or sweetviz. Sweetviz, for example, generates detailed interactive visualizations in a web browser or a notebook that help to address some of the profiling questions we raised at the beginning of the section.</p>
<p>To create a profile report for the housing prices data with sweetviz, use the following:</p>
<div id="2e0ea41a" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sweetviz <span class="im">as</span> sv</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>my_report <span class="op">=</span> sv.analyze(CA_houses)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>my_report.show_html(filepath<span class="op">=</span><span class="st">'Profiling_CA_1.html'</span>, open_browser<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"0873a8f2b1d64f22a5a877c6ed3eb0c0","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Report Profiling_CA_1.html was generated.</code></pre>
</div>
</div>
<p><a href="#fig-data-profiling1" class="quarto-xref">Figure&nbsp;<span>12.1</span></a> displays the main screen of the visualization. You can access the entire interactive html report <a href="Profiling_CA_1.html">here</a>. For each numeric variable sweetviz reports the number of observed and missing values, the number of distinct values, and a series of summary statistics similar to the output from <code>describe()</code>.&nbsp; A histogram is also produced that gives an idea of the distribution of the variable in the data set. For example, <code>housing_median_age</code> has a fairly symmetric distribution, whereas <code>total_rooms</code> and <code>total_bedrooms</code> are highly concentrated despite a wide range.</p>
<div id="fig-data-profiling1" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-profiling1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/DataProfiling_1.png" class="lightbox" data-glightbox="description: .lightbox-desc-1" data-gallery="quarto-lightbox-gallery-1"><img src="images/DataProfiling_1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-profiling1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: Sweetviz visualization for California Housing Prices. Main screen, some numeric variables.
</figcaption>
</figure>
</div>
<p><a href="#fig-data-profiling1a" class="quarto-xref">Figure&nbsp;<span>12.2</span></a> shows the bottom of the main screen that displays information on the ocean_proximity variable. We now see that there are five unique values for the variable with the majority in the category <code>&lt;1H OCEAN</code>.</p>
<div id="fig-data-profiling1a" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-profiling1a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/DataProfiling_1a.png" class="lightbox" data-glightbox="description: .lightbox-desc-2" data-gallery="quarto-lightbox-gallery-2"><img src="images/DataProfiling_1a.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-profiling1a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: Profiling information for qualitative variable <code>ocean_proximity</code>.
</figcaption>
</figure>
</div>
<p>Clicking on any variable brings up more details. For <code>housing_median_age</code> that detail is shown in <a href="#fig-data-profiling2" class="quarto-xref">Figure&nbsp;<span>12.3</span></a>. It includes a detailed histogram of the distribution, largest, smallest, and most frequent values.</p>
<div id="fig-data-profiling2" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-profiling2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/DataProfiling_2.png" class="lightbox" data-glightbox="description: .lightbox-desc-3" data-gallery="quarto-lightbox-gallery-3"><img src="images/DataProfiling_2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-profiling2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.3: Sweetviz detail for the variable <code>housing_median_age</code>.
</figcaption>
</figure>
</div>
<p>The graphics are interactive, the number of histogram columns can be changed to the desired resolution.</p>
<p>Sweetviz displays pairwise associations between variables. You can see those for <code>housing_median_age</code> in <a href="#fig-data-profiling2" class="quarto-xref">Figure&nbsp;<span>12.3</span></a> or for all pairs of variables by clicking on Associations (<a href="#fig-data-profiling3" class="quarto-xref">Figure&nbsp;<span>12.4</span></a>).</p>
<div id="fig-data-profiling3" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-profiling3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/DataProfiling_3.png" class="lightbox" data-glightbox="description: .lightbox-desc-4" data-gallery="quarto-lightbox-gallery-4"><img src="images/DataProfiling_3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-profiling3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.4: Sweetviz visualization of pairwise associations in California Housing Prices data.
</figcaption>
</figure>
</div>
<p>Associations are calculated and displayed differently depending on whether the variables in a pair are quantitative or not. For pairs of quantitative variables, sweetviz computes the Pearson correlation coefficient. It ranges from –1 to +1; a coefficient of 0 indicates no (linear) relationship between the two variables, they are uncorrelated. A coefficient of +1 indicates a perfect positive correlation, knowing one variable allows you to perfectly predict the other variable. Similarly, a Pearson coefficient of –1 means that the variables are perfectly correlated and one variable decreases as the other increases.</p>
<p>Strong positive correlations are present between <code>households</code> and the variables <code>total_rooms</code>, <code>total_bedrooms</code>, and <code>population</code>. That is expected as these variables are accumulated across all households in a block. There is a moderate positive association between median income and median house value. More expensive houses are associated with higher incomes—not surprising. A strong negative correlation exists between <code>longitude</code> and <code>latitude</code>, a consequence of the geography of California: as you move further west (east) the state reaches further south (north).&nbsp;</p>
<p>Associations between quantitative and qualitative variables are calculated as the <a href="https://en.wikipedia.org/wiki/Correlation_ratio">correlation ratio</a> that ranges from 0 to 1 and displayed as squares in the Associations matrix. The correlation ratio is based on means within the categories of the qualitative variables. A ratio of 0 means that the means of the quantitative variable are identical for all categories. Since the data contains only one qualitative variable, <code>ocean_proximity</code>, squares appear only in the last row and column of the Associations matrix.</p>
<p>If the data contains an obvious target variable for modeling, you can indicate that when creating the profiling report. Sweetviz then adds information on that variable to the visualizations. Suppose that we are interested in modeling the median house value as a function of other attributes. The following statement requests a report with <code>median_house_value</code> as the target.</p>
<div id="f7aa7487" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>housevalue_report <span class="op">=</span> sv.analyze(CA_houses, target_feat<span class="op">=</span><span class="st">"median_house_value"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>housevalue_report.show_html(filepath<span class="op">=</span><span class="st">'Profiling_CA_2.html'</span>, open_browser<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"b42fc694705343ea89a32824e1a3ae3d","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Report Profiling_CA_2.html was generated.</code></pre>
</div>
</div>
<p><a href="#fig-data-profiling4" class="quarto-xref">Figure&nbsp;<span>12.5</span></a> shows the detail on <code>ocean_proximity</code> from this analysis; the complete report is <a href="Profiling_CA_2.html">here</a>. The average of the block’s median housing values in the five groups of ocean proximity are shown on top of the histogram. The highest average median house value is found on the island, the lowest average in the inland category.</p>
<div id="fig-data-profiling4" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-profiling4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/DataProfiling_4.png" class="lightbox" data-glightbox="description: .lightbox-desc-5" data-gallery="quarto-lightbox-gallery-5"><img src="images/DataProfiling_4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-profiling4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.5: Profiling details for <code>ocean_proximity</code> with target <code>median_house_value</code>.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="sec-missing-values" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="sec-missing-values"><span class="header-section-number">12.2</span> Missing Values</h2>
<p>When observations do not have values assigned to them, we say that the value is missing. This is a fact of life in data analytics; whenever you work with a set of data you should expect values to be missing.</p>
<div class="definition">
<div class="definition-header">
<p>Definition: Missing Value</p>
</div>
<div class="definition-container">
<p>A <strong>missing value</strong> is an observation that has no value assigned to it.</p>
</div>
</div>
<p>Missingness is obvious when you see incomplete columns in the data. The problem can be inconspicuous when entire records are missing from the data. A survey that fails to include a key demographic misses the records of those who should have been sampled in the survey.</p>
<p>You should check the software packages used for data analysis on how they handle missing values—by default and how the behavior can be affected through options. In many cases the default behavior is <strong>casewise</strong> deletion, also known as <em>complete-case analysis</em>: any record that have a missing value in one or more of the analysis variables is excluded from the analysis. <strong>Pairwise</strong> deletion removes only those records that have missing values for a specific analysis. To see the difference, consider the data in <a href="#tbl-missing-data" class="quarto-xref">Table&nbsp;<span>12.1</span></a> and suppose you want to compute the matrix of correlations among the variables.</p>
<div id="tbl-missing-data" class="striped quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-missing-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12.1: Three variables with different missing value patterns.
</figcaption>
<div aria-describedby="tbl-missing-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(X_1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(X_2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(X_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">3.0</td>
<td style="text-align: center;">.</td>
</tr>
<tr class="even">
<td style="text-align: center;">2.9</td>
<td style="text-align: center;">.</td>
<td style="text-align: center;">3.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3.8</td>
<td style="text-align: center;">.</td>
<td style="text-align: center;">8.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A complete-case analysis of <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span> , and <span class="math inline">\(X_3\)</span> would result in a data frame without observations since each row of the table has a missing value in one column. Pairwise deletion computes the correlation between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> based on the first and last observation, the correlation between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_3\)</span> based on the second and third observation and fail to compute a correlation between <span class="math inline">\(X_2\)</span> and <span class="math inline">\(X_3\)</span>.</p>
<p>What are some possible causes for missing values:</p>
<ul>
<li>Members of the target population not included (missing records)</li>
<li>Data entry errors</li>
<li>Variable transformations that lead to invalid values: division by zero, logarithm of zeros or negative values</li>
<li>Measurement equipment malfunction</li>
<li>Measurement equipment limits exceeded</li>
<li>Attrition (drop-outs) of subject in longitudinal studies (death, moving, refusal, changes in medical condition, …)</li>
<li>Nonresponse of subjects in surveys</li>
<li>Variables not measured</li>
<li>Not all combinations of factors are observable. For example, the data set of your Netflix movie ratings is extremely sparse, unless you “finished Netflix” and rated all movies.</li>
<li>Regulation requires removal of sensitive information</li>
</ul>
<p>Data transformations can introduce missing values into data sets when mathematical operations are not valid. To accommodate nonlinear relationships between target and input variables, transformations of inputs such as ratios, square roots, and logarithms are common. These transformations are sometimes applied to change the distribution of data, for example, to create more symmetry by taking logarithms of right-skewed data (<a href="#fig-data-homes-log-transform" class="quarto-xref">Figure&nbsp;<span>12.6</span></a>).</p>
<div id="fig-data-homes-log-transform" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-homes-log-transform-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/HomesLogTransform.png" class="lightbox" data-glightbox="description: .lightbox-desc-6" data-gallery="quarto-lightbox-gallery-6"><img src="images/HomesLogTransform.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-homes-log-transform-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.6: Distribution of home values and logarithm of home values in Albemarle County, VA. The log-transformed data is more symmetric distributed. Since all home values are positive, the transformation does not lead to missing values.
</figcaption>
</figure>
</div>
<p>The log-transformation is meaningful in the home values example, it is not unreasonable to proceed with an analysis that assumes log(value) is normally distributed. Suppose you are log-transforming another highly skewed variable, the amount of individual’s annual medical out-of-pocket expenses. Most people have a moderate amount of out-of-pocket expenses, a smaller percentage have very high annual expenses. However, many will have no out-of-pocket expenses at all. Taking the logarithm will invalidate the records of those individuals. To get around the numerical issue of taking logarithms of zeros, transformations are sometimes changed to log(expenses + 1). This avoids missing values but fudges the data by pretending that everyone has at least some medical expenses.</p>
<p>Removing missing values from the analysis is appropriate only when the reason for the missingness is unrelated to any other information in the study. The relationship between absence of information and the study is known as the <strong>missing value process</strong>.</p>
<section id="missing-value-process" class="level3">
<h3 class="anchored" data-anchor-id="missing-value-process">Missing Value Process</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Making the wrong assumption about the missing value process can bias the results. A complete case analysis is not necessarily unbiased only if the data are missing completely at random. But the bias can at least be corrected in that case.</p>
</div>
</div>
<p>You need to be aware of three types of missing data based on that process:</p>
<ul>
<li><p><strong>MCAR</strong>: Data is said to be <strong>m</strong>issing <strong>c</strong>ompletely <strong>a</strong>t <strong>r</strong>andom when the missingness is unrelated to any study variable, including the target variable. There are no systematic differences between the records with missing data and the records with complete data. MCAR is a very strong assumption, and it is the best you can hope for. If the data are MCAR, you can safely delete records with missing values because the complete cases are a representative sample of the whole. Case deletion reduces the size of the available data but does not introduce bias into the analysis.</p></li>
<li><p><strong>MAR</strong>: Data is said to be <strong>m</strong>issing <strong>a</strong>t <strong>r</strong>andom when the pattern of missingness is related to the observed data but not to the unobserved data. Suppose you are conducting a survey regarding depression and mental health. If one group is less likely to provide information in the survey for reasons unrelated to their level of depression, then the group’s data is missing at random. Complete-case analysis of a data set that contains MAR data can result in bias.</p></li>
<li><p><strong>MNAR</strong>: Data is said to be <strong>m</strong>issing <strong>n</strong>ot <strong>a</strong>t <strong>r</strong>andom if the absence of information is systematically related to the unobserved data. For example, employees do not report salaries in a workspace survey or a group that is less likely to report in a depression survey because of their level of depression.</p></li>
</ul>
<p>A complete-case analysis if the data are MAR or MNAR does not necessarily bias the results. If the missingness is related to the primary target variable, then the results are biased. In the MAR case that bias can be corrected. As noted by the <a href="https://www.ncbi.nlm.nih.gov/books/NBK493614/">NIH</a> in the context of patient studies,</p>
<blockquote class="blockquote">
<p><em>The import of the MAR vs.&nbsp;MNAR distinction is therefore not to indicate that there definitively will or will not be bias in a complete case analysis, but instead to indicate – if the complete case analysis is biased – whether that bias can be fully removed in analysis.</em></p>
</blockquote>
<p>Missing values are represented in data sets in different ways. The two basic methods are to use masks or extra bits to indicate whether a value is available and to use sentinel value, special entries that indicate that a value is not available (missing).</p>
<div class="definition">
<div class="definition-header">
<p>Definition: Sentinel Value</p>
</div>
<div class="definition-container">
<p>In programming, a sentinel value is a special placeholder that indicates a special condition in the data or the program. Applications of sentinel values are to indicate when to break out of loops or to indicate unobserved values.</p>
</div>
</div>
<p>Sentinel values such as –9999 to indicate a missing value are dangerous, they can be mistaken too easily for a valid numerical entry. The only sentinel value one should use is NaN (not-a-number), a specially defined IEEE floating-point value. Software implements special logic for handling NaNs. Unfortunately, NaN is available only for floating point data types, so software uses different techniques to implement missing values across all data types. For example, in databases you find masking based on the concept of NULL values to indicate absence (=nullity) of a value.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Do not use sentinel values that could be confused with real data values to indicate that a value is missing.</p>
</div>
</div>
</section>
<section id="missing-values-in-pandas" class="level3">
<h3 class="anchored" data-anchor-id="missing-values-in-pandas">Missing Values in Pandas</h3>
<p>Python has the singleton object None which can be used to indicate missingness and it supports the IEEE <code>NaN</code> (not a number) to indicate missing values for floating-point types. Pandas uses the sentinel value approach based on <code>NaN</code> for floating-point and <code>None</code> for all other data types. This choice has some side effects, <code>None</code> and <code>NaN</code> do not behave the same way.</p>
<div id="035bc017" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> np.array([<span class="dv">1</span>, <span class="va">None</span>, <span class="dv">3</span>, <span class="dv">4</span>])</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>x2 <span class="op">=</span> np.array([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>])</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>display(x1)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>display(x2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>array([1, None, 3, 4], dtype=object)</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>array([1, 2, 3, 4])</code></pre>
</div>
</div>
<p>The array with <code>None</code> value is represented internally as an array of Python objects. Operating on objects is slower than on basic data types such as integers. Having missing values in non-floating-point columns thus incurs some drag on performance.</p>
<p>For floating point data use <code>np.nan</code> to indicate missingness.</p>
<div id="09ccc1e0" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>f1 <span class="op">=</span> np.array([<span class="dv">1</span>, np.nan, <span class="dv">3</span>, <span class="dv">4</span>])</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>f1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>array([ 1., nan,  3.,  4.])</code></pre>
</div>
</div>
<p>The behavior of <code>None</code> and <code>NaN</code> in operations is different. For example, arithmetic operations on <code>NaN</code>s result in <code>NaN</code>s, whereas arithmetic on <code>None</code> values results in errors.</p>
<div id="63ab2d9a" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>f1.<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>nan</code></pre>
</div>
</div>
<div id="37841eae" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>x1.<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'</code></pre>
</div>
</div>
<p>While <code>None</code> values result in errors and stop program execution, <code>NaN</code>s are contagious; they turn everything they come in touch with into <code>NaN</code>s—but the program keeps executing. Pandas mixes <code>None</code> and <code>NaN</code> values and follows casting rules when <code>np.nan</code> is stored.</p>
<div id="c867243c" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>x2 <span class="op">=</span> pd.Series([<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>], dtype<span class="op">=</span><span class="bu">int</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>display(x2)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>x2[<span class="dv">2</span>] <span class="op">=</span> np.nan</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>display(x2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>0    1
1    2
2    3
3    4
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>0    1.0
1    2.0
2    NaN
3    4.0
dtype: float64</code></pre>
</div>
</div>
<p>The integer series is converted to a float series when a <code>NaN</code> was inserted. The same happens when you use <code>None</code> instead of <code>NaN</code>:</p>
<div id="78a78f2d" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>x3 <span class="op">=</span> pd.Series([<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>], dtype<span class="op">=</span><span class="bu">int</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>x3[<span class="dv">1</span>] <span class="op">=</span> <span class="va">None</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>x3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>0    1.0
1    NaN
2    3.0
3    4.0
dtype: float64</code></pre>
</div>
</div>
</section>
<section id="working-with-missing-values-in-data-sets" class="level3">
<h3 class="anchored" data-anchor-id="working-with-missing-values-in-data-sets">Working with Missing Values in Data Sets</h3>
<p>The following statements create a Pandas DataFrame from a CSV file that contains information about 7,303 traffic collisions in New York City. You can use the info() attribute of the DataFrame for information about the columns, including missing value counts.</p>
<div id="5b56b80d" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>collisions <span class="op">=</span> pd.read_csv(<span class="st">"../datasets/nyc_collision_factors.csv"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>collisions.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 7303 entries, 0 to 7302
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   DATE                           7303 non-null   object 
 1   TIME                           7303 non-null   object 
 2   BOROUGH                        6920 non-null   object 
 3   ZIP CODE                       6919 non-null   float64
 4   LATITUDE                       7303 non-null   float64
 5   LONGITUDE                      7303 non-null   float64
 6   LOCATION                       7303 non-null   object 
 7   ON STREET NAME                 6238 non-null   object 
 8   CROSS STREET NAME              6166 non-null   object 
 9   OFF STREET NAME                761 non-null    object 
 10  NUMBER OF PERSONS INJURED      7303 non-null   int64  
 11  NUMBER OF PERSONS KILLED       7303 non-null   int64  
 12  NUMBER OF PEDESTRIANS INJURED  7303 non-null   int64  
 13  NUMBER OF PEDESTRIANS KILLED   7303 non-null   int64  
 14  NUMBER OF CYCLISTS INJURED     0 non-null      float64
 15  NUMBER OF CYCLISTS KILLED      0 non-null      float64
 16  CONTRIBUTING FACTOR VEHICLE 1  7303 non-null   object 
 17  CONTRIBUTING FACTOR VEHICLE 2  6218 non-null   object 
 18  CONTRIBUTING FACTOR VEHICLE 3  303 non-null    object 
 19  CONTRIBUTING FACTOR VEHICLE 4  59 non-null     object 
 20  CONTRIBUTING FACTOR VEHICLE 5  14 non-null     object 
 21  VEHICLE TYPE CODE 1            7245 non-null   object 
 22  VEHICLE TYPE CODE 2            5783 non-null   object 
 23  VEHICLE TYPE CODE 3            284 non-null    object 
 24  VEHICLE TYPE CODE 4            54 non-null     object 
 25  VEHICLE TYPE CODE 5            12 non-null     object 
dtypes: float64(5), int64(4), object(17)
memory usage: 1.4+ MB</code></pre>
</div>
</div>
<p>Columns <code>DATE</code> and <code>TIME</code> contain no null (missing) values, their count equals the number of observation (7,303). The number of cyclists injured or killed in the accidents in columns 14 and 15 contain only missing values. Is this a situation where the data was not entered, or should the entries be zeros? We should get back with the domain experts who put the data together to find out how to handle these columns.</p>
<p><a href="#tbl-pandas-missing" class="quarto-xref">Table&nbsp;<span>12.2</span></a> displays Pandas DataFrame methods to operate on missing values.</p>
<div id="tbl-pandas-missing" class="striped quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pandas-missing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12.2: Methods to operate on missing values in pandas DataFrames.
</figcaption>
<div aria-describedby="tbl-pandas-missing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table">
<colgroup>
<col style="width: 20%">
<col style="width: 41%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th>Description</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>isnull()</code></td>
<td>Returns a boolean same-sized object indicating if the missing values are missing</td>
<td><code>isna()</code> is an alias</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>notnull()</code></td>
<td>Opposite of <code>isnull()</code>, indicating if values are not missing</td>
<td><code>notna()</code> is an alias</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>dropna()</code></td>
<td>Remove missing values, dropping either rows (<code>axis=0</code>) or columns (<code>axis=1</code>)</td>
<td><code>how={'any','all'}</code> to determine when to drop a row or column</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>fillna()</code></td>
<td>Replace missing values with designated values</td>
<td><code>method=</code> to propagate last valid value or backfill with next valid value</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>interpolate()</code></td>
<td>Fill in missing values using an interpolation method</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The <code>isnull()</code> method can be used to return a data frame of Boolean (True/False) values that indicate missingness. You can sum across rows or columns of the data frame to count the missing values:</p>
<div id="d4270b6b" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>collisions.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>DATE                                0
TIME                                0
BOROUGH                           383
ZIP CODE                          384
LATITUDE                            0
LONGITUDE                           0
LOCATION                            0
ON STREET NAME                   1065
CROSS STREET NAME                1137
OFF STREET NAME                  6542
NUMBER OF PERSONS INJURED           0
NUMBER OF PERSONS KILLED            0
NUMBER OF PEDESTRIANS INJURED       0
NUMBER OF PEDESTRIANS KILLED        0
NUMBER OF CYCLISTS INJURED       7303
NUMBER OF CYCLISTS KILLED        7303
CONTRIBUTING FACTOR VEHICLE 1       0
CONTRIBUTING FACTOR VEHICLE 2    1085
CONTRIBUTING FACTOR VEHICLE 3    7000
CONTRIBUTING FACTOR VEHICLE 4    7244
CONTRIBUTING FACTOR VEHICLE 5    7289
VEHICLE TYPE CODE 1                58
VEHICLE TYPE CODE 2              1520
VEHICLE TYPE CODE 3              7019
VEHICLE TYPE CODE 4              7249
VEHICLE TYPE CODE 5              7291
dtype: int64</code></pre>
</div>
</div>
<p>If you choose to remove records with missing values, you can use the <code>dropna()</code> method. The <code>how=’any’|’all’</code> option specifies whether to remove records if any variable is missing (complete-case analysis) or if all variables is missing. Because the columns referring to cyclists contain only missing values, a complete-case analysis will result in an empty DataFrame.</p>
<div id="09527025" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>coll_no_miss <span class="op">=</span> collisions.dropna(how<span class="op">=</span><span class="st">'any'</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>display(<span class="bu">len</span>(collisions))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>display(<span class="bu">len</span>(coll_no_miss))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>7303</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>0</code></pre>
</div>
</div>
<p>Suppose we verified that the missing values in columns 14 &amp; 15 were meant to indicate that no cyclists were injured or killed. Then we can replace the missing values with zeros using the <code>fillna()</code> method.</p>
<div id="331bc8a0" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>collisions[<span class="st">"NUMBER OF CYCLISTS INJURED"</span>].fillna(<span class="dv">0</span>,inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>collisions[<span class="st">"NUMBER OF CYCLISTS KILLED"</span>].fillna(<span class="dv">0</span>,inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/ff/6m670wks1776ck_gbfxynxrc0000gq/T/ipykernel_12993/612697346.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/var/folders/ff/6m670wks1776ck_gbfxynxrc0000gq/T/ipykernel_12993/612697346.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


</code></pre>
</div>
</div>
<p>Techniques for imputing missing values are discussed in more detail below.</p>
<p>The <code>notnull()</code> method is useful to select records without missing values. Since it returns a boolean same-sized object, you can use it to filter:</p>
<div id="2d0267c6" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>bool_series <span class="op">=</span> pd.notnull(collisions[<span class="st">"CONTRIBUTING FACTOR VEHICLE 5"</span>]) </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>collisions.loc[bool_series, [<span class="st">"DATE"</span>, <span class="st">"TIME"</span>, <span class="st">"BOROUGH"</span>, <span class="st">"ON STREET NAME"</span>]] </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">DATE</th>
<th data-quarto-table-cell-role="th">TIME</th>
<th data-quarto-table-cell-role="th">BOROUGH</th>
<th data-quarto-table-cell-role="th">ON STREET NAME</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">217</td>
<td>04/11/2016</td>
<td>13:22:00</td>
<td>BROOKLYN</td>
<td>STUYVESANT AVENUE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">896</td>
<td>10/08/2016</td>
<td>14:10:00</td>
<td>QUEENS</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1112</td>
<td>10/18/2016</td>
<td>07:10:00</td>
<td>QUEENS</td>
<td>124 STREET</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1348</td>
<td>11/23/2016</td>
<td>14:11:00</td>
<td>BROOKLYN</td>
<td>SUTTER AVENUE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1551</td>
<td>11/16/2016</td>
<td>11:11:00</td>
<td>QUEENS</td>
<td>112 AVENUE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1554</td>
<td>11/29/2016</td>
<td>04:11:00</td>
<td>BROOKLYN</td>
<td>SNYDER AVENUE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2794</td>
<td>11/15/2016</td>
<td>03:11:00</td>
<td>MANHATTAN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2899</td>
<td>03/07/2016</td>
<td>08:45:00</td>
<td>QUEENS</td>
<td>105 AVENUE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3292</td>
<td>10/25/2016</td>
<td>18:10:00</td>
<td>BROOKLYN</td>
<td>HIGHLAND BOULEVARD</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3813</td>
<td>10/03/2016</td>
<td>17:10:00</td>
<td>STATEN ISLAND</td>
<td>MANOR ROAD</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4346</td>
<td>02/08/2016</td>
<td>12:08:00</td>
<td>BROOKLYN</td>
<td>EAST 35 STREET</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5286</td>
<td>01/14/2016</td>
<td>20:00:00</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5556</td>
<td>01/07/2016</td>
<td>18:50:00</td>
<td>QUEENS</td>
<td>31 AVENUE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6737</td>
<td>01/11/2016</td>
<td>09:03:00</td>
<td>BROOKLYN</td>
<td>BROADWAY</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="visualizing-missing-value-patterns" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-missing-value-patterns">Visualizing Missing Value Patterns</h3>
<p>The <a href="https://github.com/ResidentMario/missingno">Missingno</a> Python package has some nice methods to inspect the missing value patterns in data. This is helpful to see the missing value distribution across multiple columns. The <code>matrix()</code> method displays the missing value pattern for the DataFrame.</p>
<div id="80977816" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> missingno <span class="im">as</span> msno</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>msno.matrix(collisions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="quality_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Columns without missing values (DATE, TIME) are shown as a solid gray bar. Missing values are displayed in white. The following graph shows the result of <code>matrix()</code> prior to filling in zeros in the cyclist columns. The sparkline at right summarizes the general shape of the data completeness and points out the rows with the maximum and minimum number of missing values in the dataset. At best 11 of the columns have missing values, at worst 23 of the 26 values are missing.</p>
<p><a href="#tbl-sales-data" class="quarto-xref">Table&nbsp;<span>12.3</span></a> contains data on property sales. The total value of the property is the sum of the first two columns, the last column is the ratio between sales price and total value. A missing value in one of the first two columns triggers a missing value in the <code>Total</code> column. If either <code>Total</code> or <code>Sales</code> are not present, the appraisal ratio in the last column must be missing.</p>
<div id="tbl-sales-data" class="striped quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sales-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12.3: Data with column dependencies that propagate missing values.
</figcaption>
<div aria-describedby="tbl-sales-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table">
<thead>
<tr class="header">
<th style="text-align: right;">Land</th>
<th style="text-align: right;">Improvements</th>
<th style="text-align: right;">Total</th>
<th style="text-align: right;">Sale</th>
<th style="text-align: right;">Appraisal Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">30000</td>
<td style="text-align: right;">64831</td>
<td style="text-align: right;">94831</td>
<td style="text-align: right;">118500</td>
<td style="text-align: right;">1.25</td>
</tr>
<tr class="even">
<td style="text-align: right;">30000</td>
<td style="text-align: right;">50765</td>
<td style="text-align: right;">80765</td>
<td style="text-align: right;">93900</td>
<td style="text-align: right;">1.16</td>
</tr>
<tr class="odd">
<td style="text-align: right;">46651</td>
<td style="text-align: right;">18573</td>
<td style="text-align: right;">65224</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">.</td>
</tr>
<tr class="even">
<td style="text-align: right;">45990</td>
<td style="text-align: right;">91402</td>
<td style="text-align: right;">137392</td>
<td style="text-align: right;">184000</td>
<td style="text-align: right;">1.34</td>
</tr>
<tr class="odd">
<td style="text-align: right;">42394</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">168000</td>
<td style="text-align: right;">.</td>
</tr>
<tr class="even">
<td style="text-align: right;">.</td>
<td style="text-align: right;">133351</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">169000</td>
<td style="text-align: right;">.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">63596</td>
<td style="text-align: right;">2182</td>
<td style="text-align: right;">65778</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">.</td>
</tr>
<tr class="even">
<td style="text-align: right;">56658</td>
<td style="text-align: right;">153806</td>
<td style="text-align: right;">210464</td>
<td style="text-align: right;">255000</td>
<td style="text-align: right;">1.21</td>
</tr>
<tr class="odd">
<td style="text-align: right;">51428</td>
<td style="text-align: right;">72451</td>
<td style="text-align: right;">123879</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">.</td>
</tr>
<tr class="even">
<td style="text-align: right;">93200</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">422000</td>
<td style="text-align: right;">.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">76125</td>
<td style="text-align: right;">78172</td>
<td style="text-align: right;">275297</td>
<td style="text-align: right;">290000</td>
<td style="text-align: right;">1.14</td>
</tr>
<tr class="even">
<td style="text-align: right;">154360</td>
<td style="text-align: right;">61934</td>
<td style="text-align: right;">216294</td>
<td style="text-align: right;">237000</td>
<td style="text-align: right;">1.10</td>
</tr>
<tr class="odd">
<td style="text-align: right;">65376</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">286500</td>
<td style="text-align: right;">.</td>
</tr>
<tr class="even">
<td style="text-align: right;">42400</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">.</td>
<td style="text-align: right;">.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">40800</td>
<td style="text-align: right;">92606</td>
<td style="text-align: right;">133406</td>
<td style="text-align: right;">168000</td>
<td style="text-align: right;">1.26</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The <code>heatmap()</code> method shows a matrix of nullity correlations between the columns of the data. Note that the CSV file contains dots (“.”) for the missing values. To make sure the data are correctly converted to numerical types and the dots are interpreted as missing values, the <code>na_values=</code> and <code>skipinitalspace=</code> options are added to <code>pd.read_csv()</code>.</p>
<div id="9a212993" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>land <span class="op">=</span> pd.read_csv(<span class="st">"../datasets/landsales.csv"</span>, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                   na_values<span class="op">=</span><span class="st">"."</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                   skipinitialspace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>msno.heatmap(land)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="quality_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The nullity correlations are Pearson correlation coefficients computed from the <code>isnull()</code> boolean object for the data, excluding columns that are completely observed or completely unobserved. A correlation of –1 means that presence/absence of two variables is perfectly correlated: if one variable appears the other variable does not appear. A correlation of +1 similarly means that the presence of one variable goes together with the presence of another variable. The <code>total</code> is not perfectly correlated with <code>land</code> or <code>improve</code> columns because a null value in either or both of these can cause a null value for the total. Similarly, the large correlations between appraisal &amp; total and appraisal &amp; sale are indicative that their missing values are likely to occur together.</p>
</section>
<section id="data-imputation" class="level3">
<h3 class="anchored" data-anchor-id="data-imputation">Data Imputation</h3>
<p>In a previous example we used the <code>fillna()</code> method to replace missing values with actual values: the unobserved values for the number of cyclists in the collisions data set were interpreted as no cyclists were injured, replacing <code>NaN</code>s with zeros. This is an example of data imputation.</p>
<div class="definition">
<div class="definition-header">
<p>Definition: Data Imputation</p>
</div>
<div class="definition-container">
<p>Data imputation is the process of replacing unobserved (missing) values with usable values.<br>
</p>
</div>
</div>
<p>Imputation must be carried out with care. It is tempting to replace absent values with numbers and to complete the data: records are not removed from the analysis, the sample size is maintained, and calculations no longer fail. Imputing values that are not representative introduces bias into the data.</p>
<p>Completing missing values based on information in other columns often seems simple on the surface, but it is fraught with difficulties—there be dragons! Suppose using address information to fill in missing zip codes. It is not sufficient to know that the city is Blacksburg. If we are talking about Blacksburg, SC, then we know the ZIP code is 29702. If it is Blacksburg, VA, however, then there are four possible ZIP codes; we need the street address to resolve to a unique value. Inferring a missing attribute such as gender should never be done. You cannot safely do it using names. Individuals might have chosen to not report gender information. You cannot afford to get it wrong.</p>
<p>If string-type data is missing, and you want to include them into the analysis, you can replace the missing values with an identifying string such as “Unobserved” or “Unknown”. That allows you to break out results for these observations in group-by observations, for example.</p>
<p>If you decide to proceed with imputation of missing values based on algorithms, here are some options:</p>
<ul>
<li><p><strong>Random replacement</strong>. Also called hot-deck imputation, the missing value is replaced with a randomly selected similar record in the same data set that has complete information.</p></li>
<li><p><strong>LOCF</strong>. The missing value is replaced with the last complete observation preceding it: the <strong>l</strong>ast <strong>o</strong>bservation is <strong>c</strong>arried <strong>f</strong>orward. It is also called a forward fill. This method requires that the order of the observations in the data is somehow meaningful. If observations are grouped by city, it is probable that a missing value for the city column represents the same city as the previous record, unless the missing value falls on the record boundary between two cities.</p></li>
<li><p><strong>Backfill</strong>. This is the opposite of LOCF; the next complete value following one or more missing values is propagated backwards.</p></li>
<li><p><strong>Mean/Median imputation</strong>. This technique applies to numeric data; the missing value is replaced based on the sample mean, the sample median, or other statistical measures of location calculated from the non-missing values in a column. If the data consists of groups or classes, then group-specific means can be used. For example, if the data comprises age groups or genders, then missing values for a numeric variable can be replaced with averages for the variabler by age groups or genders.</p></li>
<li><p><strong>Interpolation methods</strong>. For numerical data, missing values can be interpolated from nearby values. Interpolation calculations are based on linear, polynomial, or spline methods. Using the interpolate() method in pandas, you can choose between interpolating across rows or columns of the DataFrame.</p></li>
<li><p><strong>Regression imputation</strong>. The column with missing values is treated as the target variable of a regression model, using one or more other columns as input variables of the regression. The missing values are then treated as unobserved observations for which the target is predicted.</p></li>
<li><p><strong>Matrix completion</strong>. Based on principal component analysis, missing values in a <span class="math inline">\(r \times c\)</span> numerical array are replaced with a low-rank approximation of the missing values based on the observed values.</p></li>
<li><p><strong>Generative imputation</strong>. If the data consists of images or text and portions are unobserved, for example, parts of the image are obscured, then generative methods can be used to fill in missing pixels in the image or missing words in text.</p></li>
</ul>
<p>To demonstrate some of these techniques, consider this simple 6 x 3 DataFrame.</p>
<div id="a2b5bbb8" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(np.random.standard_normal((<span class="dv">6</span>, <span class="dv">3</span>)))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>df.iloc[:<span class="dv">4</span>,<span class="dv">1</span>] <span class="op">=</span> np.nan</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>df.iloc[<span class="dv">1</span>:<span class="dv">3</span>,<span class="dv">2</span>] <span class="op">=</span> np.nan</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.496714</td>
<td>NaN</td>
<td>0.647689</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.523030</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.579213</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.542560</td>
<td>NaN</td>
<td>-0.465730</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.241962</td>
<td>-1.913280</td>
<td>-1.724918</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>-0.562288</td>
<td>-1.012831</td>
<td>0.314247</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>You can choose a common fill value for all columns or vary the value by column.</p>
<div id="9dd2533b" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>df.fillna({<span class="dv">1</span>:<span class="fl">0.3</span>, <span class="dv">2</span>:<span class="dv">0</span>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.496714</td>
<td>0.300000</td>
<td>0.647689</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.523030</td>
<td>0.300000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.579213</td>
<td>0.300000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.542560</td>
<td>0.300000</td>
<td>-0.465730</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.241962</td>
<td>-1.913280</td>
<td>-1.724918</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>-0.562288</td>
<td>-1.012831</td>
<td>0.314247</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>Missing values in the second column are replaced with 0.3, those in the last column with zero. Forward (LOCF) and backward imputation are available by setting the <code>method=</code> parameter of <code>fillna()</code>:</p>
<div id="3d0c2a7c" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df.fillna(method<span class="op">=</span><span class="st">"ffill"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/ff/6m670wks1776ck_gbfxynxrc0000gq/T/ipykernel_12993/3944122520.py:1: FutureWarning:

DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.496714</td>
<td>NaN</td>
<td>0.647689</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.523030</td>
<td>NaN</td>
<td>0.647689</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.579213</td>
<td>NaN</td>
<td>0.647689</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.542560</td>
<td>NaN</td>
<td>-0.465730</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.241962</td>
<td>-1.913280</td>
<td>-1.724918</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>-0.562288</td>
<td>-1.012831</td>
<td>0.314247</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>Notice that the forward fill does not replace the <code>NaN</code>s in the second column as there is no non-missing last value to be carried forward. The second and third row in the third column are imputed by carrying forward 0.647689 from the first row. With a backfill imputation the DataFrame is fully completed, since both columns have an observed value after the last missing value.</p>
<div id="e02211a8" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>df.fillna(method<span class="op">=</span><span class="st">"bfill"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/ff/6m670wks1776ck_gbfxynxrc0000gq/T/ipykernel_12993/3896554658.py:1: FutureWarning:

DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.496714</td>
<td>-1.913280</td>
<td>0.647689</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.523030</td>
<td>-1.913280</td>
<td>-0.465730</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.579213</td>
<td>-1.913280</td>
<td>-0.465730</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.542560</td>
<td>-1.913280</td>
<td>-0.465730</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.241962</td>
<td>-1.913280</td>
<td>-1.724918</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>-0.562288</td>
<td>-1.012831</td>
<td>0.314247</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>To replace the missing values with the column-specific sample means, simply use</p>
<div id="a605957e" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>df.fillna(df.mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.496714</td>
<td>-1.463056</td>
<td>0.647689</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.523030</td>
<td>-1.463056</td>
<td>-0.307178</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.579213</td>
<td>-1.463056</td>
<td>-0.307178</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.542560</td>
<td>-1.463056</td>
<td>-0.465730</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.241962</td>
<td>-1.913280</td>
<td>-1.724918</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>-0.562288</td>
<td>-1.012831</td>
<td>0.314247</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>The sample means of the non-missing observations in the second and third columns are -1.463056 and -0.307178, respectively. Imputing with the sample mean has the nice property to preserve the sample mean of the completed data:]</p>
<div id="9660e4c2" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>df.fillna(df.mean()).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>0    0.636865
1   -1.463056
2   -0.307178
dtype: float64</code></pre>
</div>
</div>
<p>You can use other location statistics than the mean. The following statement imputes with the column-specific sample median:</p>
<div id="9f4b44ca" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>df.fillna(df.median())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.496714</td>
<td>-1.463056</td>
<td>0.647689</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.523030</td>
<td>-1.463056</td>
<td>-0.075741</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.579213</td>
<td>-1.463056</td>
<td>-0.075741</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.542560</td>
<td>-1.463056</td>
<td>-0.465730</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.241962</td>
<td>-1.913280</td>
<td>-1.724918</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>-0.562288</td>
<td>-1.012831</td>
<td>0.314247</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>To demonstrate imputation by interpolation, consider this simple series:</p>
<div id="3d7d0740" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> pd.Series([<span class="dv">0</span>, <span class="dv">2</span>, np.nan, <span class="dv">8</span>])</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>s</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>0    0.0
1    2.0
2    NaN
3    8.0
dtype: float64</code></pre>
</div>
</div>
<p>The default interpolation method is linear interpolation. You can choose other method, for example, spline or polynomial interpolation, with the <code>method=</code> option.</p>
<div id="e7eb88ea" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>s.interpolate()</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>s.interpolate(method<span class="op">=</span><span class="st">'polynomial'</span>, order<span class="op">=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>0    0.000000
1    2.000000
2    4.666667
3    8.000000
dtype: float64</code></pre>
</div>
</div>
<p>To see interpolation operate on a DataFrame, consider this example:</p>
<div id="20a625c8" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame([(<span class="fl">0.0</span>, np.nan, <span class="op">-</span><span class="fl">1.0</span>, <span class="fl">1.0</span>),</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>                    (np.nan, <span class="fl">2.0</span>, np.nan, np.nan),</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                    (<span class="fl">2.0</span>, <span class="fl">3.0</span>, np.nan, <span class="fl">9.0</span>),</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                    (np.nan, <span class="fl">4.0</span>, <span class="op">-</span><span class="fl">4.0</span>, <span class="fl">16.0</span>)],</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                   columns<span class="op">=</span><span class="bu">list</span>(<span class="st">'abcd'</span>))</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">a</th>
<th data-quarto-table-cell-role="th">b</th>
<th data-quarto-table-cell-role="th">c</th>
<th data-quarto-table-cell-role="th">d</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.0</td>
<td>NaN</td>
<td>-1.0</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>NaN</td>
<td>2.0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2.0</td>
<td>3.0</td>
<td>NaN</td>
<td>9.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>NaN</td>
<td>4.0</td>
<td>-4.0</td>
<td>16.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>The default interpolation method is linear with a forward direction across rows.</p>
<div id="3990527c" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>df.interpolate()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">a</th>
<th data-quarto-table-cell-role="th">b</th>
<th data-quarto-table-cell-role="th">c</th>
<th data-quarto-table-cell-role="th">d</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.0</td>
<td>NaN</td>
<td>-1.0</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.0</td>
<td>2.0</td>
<td>-2.0</td>
<td>5.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2.0</td>
<td>3.0</td>
<td>-3.0</td>
<td>9.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2.0</td>
<td>4.0</td>
<td>-4.0</td>
<td>16.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>Because there was no observed value preceding the missing value in column <code>b</code>, the <code>NaN</code> cannot be interpolated. Because there was no value past the last missing value in column <code>a</code>, the <code>NaN</code> is replaced with the last value carried forward.</p>
<p>To interpolate in the forward and backward direction, use <code>limit_direction=’both’</code>:</p>
<div id="52ba6309" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>df.interpolate(method<span class="op">=</span><span class="st">'linear'</span>, limit_direction<span class="op">=</span><span class="st">'both'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">a</th>
<th data-quarto-table-cell-role="th">b</th>
<th data-quarto-table-cell-role="th">c</th>
<th data-quarto-table-cell-role="th">d</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.0</td>
<td>2.0</td>
<td>-1.0</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.0</td>
<td>2.0</td>
<td>-2.0</td>
<td>5.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2.0</td>
<td>3.0</td>
<td>-3.0</td>
<td>9.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2.0</td>
<td>4.0</td>
<td>-4.0</td>
<td>16.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>To interpolate across the columns, set the <code>axis=</code> option to <code>axis=1</code>:</p>
<div id="66adc246" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>df.interpolate(method<span class="op">=</span><span class="st">'linear'</span>, limit_direction<span class="op">=</span><span class="st">'forward'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">a</th>
<th data-quarto-table-cell-role="th">b</th>
<th data-quarto-table-cell-role="th">c</th>
<th data-quarto-table-cell-role="th">d</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.0</td>
<td>-0.5</td>
<td>-1.0</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>NaN</td>
<td>2.0</td>
<td>2.0</td>
<td>2.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2.0</td>
<td>3.0</td>
<td>6.0</td>
<td>9.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>NaN</td>
<td>4.0</td>
<td>-4.0</td>
<td>16.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>Imputation seems convenient and relatively simple, and there are many methods to choose from. As you can see from this discussion, there are also many issues and pitfalls. Besides introducing potential bias by imputing with bad values, an important issue is the level of uncertainty associated with imputed values. Unless the data were measured with error or entered incorrectly, you have confidence in the observed values. You cannot have the same level of confidence in the imputed values. The imputed values are estimates based on processes that involve randomness. One source of randomness is that our data represents a random sample—a different set of data gives a different estimate for the missing value. Another source of randomness is the imputation method itself. For example, hot-deck imputation chooses the imputed value based on randomly selected observations with complete data.</p>
<p>Accounting for these multiple levels of uncertainty is non-trivial. If you pass imputed data to any statistical algorithm, it will assume that all values are known with the same level of confidence. There are ways to take imputation uncertainty into account. You can assign weights to the observations where the weight is proportional to your level of confidence. Assigning smaller weights to imputed values reduces their impact on the analysis. A better approach is to use <strong>bootstrap</strong> techniques to capture the true uncertainty and bias in the quantities derived from imputed data. This is more computer intensive than a weighted analysis but very doable with today’s computing power.</p>
<div class="definition">
<div class="definition-header">
<p>Definition: Bootstrap</p>
</div>
<div class="definition-container">
<p>To bootstrap a data set is to repeatedly sample from the data with replacement. Suppose you have a data set of size <span class="math inline">\(n\)</span> rows. <span class="math inline">\(B\)</span> = 1,000 bootstrap samples are 1,000 data sets of size <span class="math inline">\(n\)</span>, each drawn independently from each other, and the observations in each bootstrap sample are drawn with replacement.</p>
<p>Bootstrapping is a statistical technique to derive the sample distribution of a random quantity by simulation. You apply the technique to each bootstrap sample and average the results.</p>
</div>
</div>
<p>I hope you take away from this discussion that imputation is possible, imputation is not always necessary, and imputation must be done with care.</p>
</section>
</section>
<section id="outlier-and-anomalies" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="outlier-and-anomalies"><span class="header-section-number">12.3</span> Outlier and Anomalies</h2>
</section>
<section id="unbalanced-data" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="unbalanced-data"><span class="header-section-number">12.4</span> Unbalanced Data</h2>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Figure&nbsp;12.1: Sweetviz visualization for California Housing Prices. Main screen, some numeric variables.</span>
<span class="glightbox-desc lightbox-desc-2">Figure&nbsp;12.2: Profiling information for qualitative variable <code>ocean_proximity</code>.</span>
<span class="glightbox-desc lightbox-desc-3">Figure&nbsp;12.3: Sweetviz detail for the variable <code>housing_median_age</code>.</span>
<span class="glightbox-desc lightbox-desc-4">Figure&nbsp;12.4: Sweetviz visualization of pairwise associations in California Housing Prices data.</span>
<span class="glightbox-desc lightbox-desc-5">Figure&nbsp;12.5: Profiling details for <code>ocean_proximity</code> with target <code>median_house_value</code>.</span>
<span class="glightbox-desc lightbox-desc-6">Figure&nbsp;12.6: Distribution of home values and logarithm of home values in Albemarle County, VA. The log-transformed data is more symmetric distributed. Since all home values are positive, the transformation does not lead to missing values.</span>
</div>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Borne_2021_profiling" class="csl-entry" role="listitem">
Borne, Kirk. 2021. <span>“Data Profiling–Having That First Data with Your Data.”</span> <em>Medium</em>. <a href="https://medium.com/codex/data-profiling-having-that-first-date-with-your-data-2e05de50fca7">https://medium.com/codex/data-profiling-having-that-first-date-with-your-data-2e05de50fca7</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script type="application/vnd.jupyter.widget-state+json">
{"state":{"00a77c70593548c7a762d7d5370a0451":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HTMLModel","state":{"_dom_classes":[],"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HTMLModel","_view_count":null,"_view_module":"@jupyter-widgets/controls","_view_module_version":"2.0.0","_view_name":"HTMLView","description":"","description_allow_html":false,"layout":"IPY_MODEL_70eabb3039244a24b8b563f51ce39212","placeholder":"​","style":"IPY_MODEL_f74e24c0b5ed48ca94bd2f3aaafd8b6c","tabbable":null,"tooltip":null,"value":"Done! Use &#x27;show&#x27; commands to display/save.   "}},"0873a8f2b1d64f22a5a877c6ed3eb0c0":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HBoxModel","state":{"_dom_classes":[],"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HBoxModel","_view_count":null,"_view_module":"@jupyter-widgets/controls","_view_module_version":"2.0.0","_view_name":"HBoxView","box_style":"","children":["IPY_MODEL_edf56cf2b7e1471db4c1f57e27baaa8c","IPY_MODEL_8c62aa63057e484486a79534f08c24c2","IPY_MODEL_43d2ab4bc5ea4c529547af0388066d97"],"layout":"IPY_MODEL_f99570e497694749aecea46fb29443d9","tabbable":null,"tooltip":null}},"13b31d3c83f743149d02139d04f5bd19":{"model_module":"@jupyter-widgets/base","model_module_version":"2.0.0","model_name":"LayoutModel","state":{"_model_module":"@jupyter-widgets/base","_model_module_version":"2.0.0","_model_name":"LayoutModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"LayoutView","align_content":null,"align_items":null,"align_self":null,"border_bottom":null,"border_left":null,"border_right":null,"border_top":null,"bottom":null,"display":null,"flex":"2","flex_flow":null,"grid_area":null,"grid_auto_columns":null,"grid_auto_flow":null,"grid_auto_rows":null,"grid_column":null,"grid_gap":null,"grid_row":null,"grid_template_areas":null,"grid_template_columns":null,"grid_template_rows":null,"height":null,"justify_content":null,"justify_items":null,"left":null,"margin":null,"max_height":null,"max_width":null,"min_height":null,"min_width":null,"object_fit":null,"object_position":null,"order":null,"overflow":null,"padding":null,"right":null,"top":null,"visibility":null,"width":null}},"241b55660917495c8755e6699161df75":{"model_module":"@jupyter-widgets/base","model_module_version":"2.0.0","model_name":"LayoutModel","state":{"_model_module":"@jupyter-widgets/base","_model_module_version":"2.0.0","_model_name":"LayoutModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"LayoutView","align_content":null,"align_items":null,"align_self":null,"border_bottom":null,"border_left":null,"border_right":null,"border_top":null,"bottom":null,"display":null,"flex":null,"flex_flow":null,"grid_area":null,"grid_auto_columns":null,"grid_auto_flow":null,"grid_auto_rows":null,"grid_column":null,"grid_gap":null,"grid_row":null,"grid_template_areas":null,"grid_template_columns":null,"grid_template_rows":null,"height":null,"justify_content":null,"justify_items":null,"left":null,"margin":null,"max_height":null,"max_width":null,"min_height":null,"min_width":null,"object_fit":null,"object_position":null,"order":null,"overflow":null,"padding":null,"right":null,"top":null,"visibility":null,"width":null}},"43d2ab4bc5ea4c529547af0388066d97":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HTMLModel","state":{"_dom_classes":[],"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HTMLModel","_view_count":null,"_view_module":"@jupyter-widgets/controls","_view_module_version":"2.0.0","_view_name":"HTMLView","description":"","description_allow_html":false,"layout":"IPY_MODEL_5eebc5aeb68e4cd2b82b8b79c2ebc2df","placeholder":"​","style":"IPY_MODEL_a8b929efda4c4bbab6c310d351ad288c","tabbable":null,"tooltip":null,"value":" [100%]   00:00 -&gt; (00:00 left)"}},"52ad0c39b5564249bb8a63b743a75e04":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HTMLStyleModel","state":{"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HTMLStyleModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"StyleView","background":null,"description_width":"","font_size":null,"text_color":null}},"5eebc5aeb68e4cd2b82b8b79c2ebc2df":{"model_module":"@jupyter-widgets/base","model_module_version":"2.0.0","model_name":"LayoutModel","state":{"_model_module":"@jupyter-widgets/base","_model_module_version":"2.0.0","_model_name":"LayoutModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"LayoutView","align_content":null,"align_items":null,"align_self":null,"border_bottom":null,"border_left":null,"border_right":null,"border_top":null,"bottom":null,"display":null,"flex":null,"flex_flow":null,"grid_area":null,"grid_auto_columns":null,"grid_auto_flow":null,"grid_auto_rows":null,"grid_column":null,"grid_gap":null,"grid_row":null,"grid_template_areas":null,"grid_template_columns":null,"grid_template_rows":null,"height":null,"justify_content":null,"justify_items":null,"left":null,"margin":null,"max_height":null,"max_width":null,"min_height":null,"min_width":null,"object_fit":null,"object_position":null,"order":null,"overflow":null,"padding":null,"right":null,"top":null,"visibility":null,"width":null}},"70eabb3039244a24b8b563f51ce39212":{"model_module":"@jupyter-widgets/base","model_module_version":"2.0.0","model_name":"LayoutModel","state":{"_model_module":"@jupyter-widgets/base","_model_module_version":"2.0.0","_model_name":"LayoutModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"LayoutView","align_content":null,"align_items":null,"align_self":null,"border_bottom":null,"border_left":null,"border_right":null,"border_top":null,"bottom":null,"display":null,"flex":null,"flex_flow":null,"grid_area":null,"grid_auto_columns":null,"grid_auto_flow":null,"grid_auto_rows":null,"grid_column":null,"grid_gap":null,"grid_row":null,"grid_template_areas":null,"grid_template_columns":null,"grid_template_rows":null,"height":null,"justify_content":null,"justify_items":null,"left":null,"margin":null,"max_height":null,"max_width":null,"min_height":null,"min_width":null,"object_fit":null,"object_position":null,"order":null,"overflow":null,"padding":null,"right":null,"top":null,"visibility":null,"width":null}},"7b1da95a2ee94f4e8d87d74d9709bb49":{"model_module":"@jupyter-widgets/base","model_module_version":"2.0.0","model_name":"LayoutModel","state":{"_model_module":"@jupyter-widgets/base","_model_module_version":"2.0.0","_model_name":"LayoutModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"LayoutView","align_content":null,"align_items":null,"align_self":null,"border_bottom":null,"border_left":null,"border_right":null,"border_top":null,"bottom":null,"display":"inline-flex","flex":null,"flex_flow":"row wrap","grid_area":null,"grid_auto_columns":null,"grid_auto_flow":null,"grid_auto_rows":null,"grid_column":null,"grid_gap":null,"grid_row":null,"grid_template_areas":null,"grid_template_columns":null,"grid_template_rows":null,"height":null,"justify_content":null,"justify_items":null,"left":null,"margin":null,"max_height":null,"max_width":null,"min_height":null,"min_width":null,"object_fit":null,"object_position":null,"order":null,"overflow":null,"padding":null,"right":null,"top":null,"visibility":null,"width":"100%"}},"82920a556ac9498a8ffddf7f999c9c57":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"ProgressStyleModel","state":{"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"ProgressStyleModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"StyleView","bar_color":null,"description_width":""}},"83af913793cc4601bade5defb37f0e79":{"model_module":"@jupyter-widgets/base","model_module_version":"2.0.0","model_name":"LayoutModel","state":{"_model_module":"@jupyter-widgets/base","_model_module_version":"2.0.0","_model_name":"LayoutModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"LayoutView","align_content":null,"align_items":null,"align_self":null,"border_bottom":null,"border_left":null,"border_right":null,"border_top":null,"bottom":null,"display":null,"flex":null,"flex_flow":null,"grid_area":null,"grid_auto_columns":null,"grid_auto_flow":null,"grid_auto_rows":null,"grid_column":null,"grid_gap":null,"grid_row":null,"grid_template_areas":null,"grid_template_columns":null,"grid_template_rows":null,"height":null,"justify_content":null,"justify_items":null,"left":null,"margin":null,"max_height":null,"max_width":null,"min_height":null,"min_width":null,"object_fit":null,"object_position":null,"order":null,"overflow":null,"padding":null,"right":null,"top":null,"visibility":null,"width":null}},"8c62aa63057e484486a79534f08c24c2":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"FloatProgressModel","state":{"_dom_classes":[],"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"FloatProgressModel","_view_count":null,"_view_module":"@jupyter-widgets/controls","_view_module_version":"2.0.0","_view_name":"ProgressView","bar_style":"success","description":"","description_allow_html":false,"layout":"IPY_MODEL_c0721bec5e7541af9913f05f6a183650","max":1,"min":0,"orientation":"horizontal","style":"IPY_MODEL_82920a556ac9498a8ffddf7f999c9c57","tabbable":null,"tooltip":null,"value":1}},"a8b929efda4c4bbab6c310d351ad288c":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HTMLStyleModel","state":{"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HTMLStyleModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"StyleView","background":null,"description_width":"","font_size":null,"text_color":null}},"b42fc694705343ea89a32824e1a3ae3d":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HBoxModel","state":{"_dom_classes":[],"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HBoxModel","_view_count":null,"_view_module":"@jupyter-widgets/controls","_view_module_version":"2.0.0","_view_name":"HBoxView","box_style":"","children":["IPY_MODEL_00a77c70593548c7a762d7d5370a0451","IPY_MODEL_e02ae3365acc471f832f09701311488a","IPY_MODEL_f8313a80920e4f9991be71ac44ff1738"],"layout":"IPY_MODEL_7b1da95a2ee94f4e8d87d74d9709bb49","tabbable":null,"tooltip":null}},"c0721bec5e7541af9913f05f6a183650":{"model_module":"@jupyter-widgets/base","model_module_version":"2.0.0","model_name":"LayoutModel","state":{"_model_module":"@jupyter-widgets/base","_model_module_version":"2.0.0","_model_name":"LayoutModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"LayoutView","align_content":null,"align_items":null,"align_self":null,"border_bottom":null,"border_left":null,"border_right":null,"border_top":null,"bottom":null,"display":null,"flex":"2","flex_flow":null,"grid_area":null,"grid_auto_columns":null,"grid_auto_flow":null,"grid_auto_rows":null,"grid_column":null,"grid_gap":null,"grid_row":null,"grid_template_areas":null,"grid_template_columns":null,"grid_template_rows":null,"height":null,"justify_content":null,"justify_items":null,"left":null,"margin":null,"max_height":null,"max_width":null,"min_height":null,"min_width":null,"object_fit":null,"object_position":null,"order":null,"overflow":null,"padding":null,"right":null,"top":null,"visibility":null,"width":null}},"c0a35a753b7246699c6e413d48e30ae0":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"ProgressStyleModel","state":{"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"ProgressStyleModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"StyleView","bar_color":null,"description_width":""}},"c7ef59cc73014fbdb6b1dba7dfe1f604":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HTMLStyleModel","state":{"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HTMLStyleModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"StyleView","background":null,"description_width":"","font_size":null,"text_color":null}},"e02ae3365acc471f832f09701311488a":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"FloatProgressModel","state":{"_dom_classes":[],"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"FloatProgressModel","_view_count":null,"_view_module":"@jupyter-widgets/controls","_view_module_version":"2.0.0","_view_name":"ProgressView","bar_style":"success","description":"","description_allow_html":false,"layout":"IPY_MODEL_13b31d3c83f743149d02139d04f5bd19","max":1,"min":0,"orientation":"horizontal","style":"IPY_MODEL_c0a35a753b7246699c6e413d48e30ae0","tabbable":null,"tooltip":null,"value":1}},"edf56cf2b7e1471db4c1f57e27baaa8c":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HTMLModel","state":{"_dom_classes":[],"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HTMLModel","_view_count":null,"_view_module":"@jupyter-widgets/controls","_view_module_version":"2.0.0","_view_name":"HTMLView","description":"","description_allow_html":false,"layout":"IPY_MODEL_241b55660917495c8755e6699161df75","placeholder":"​","style":"IPY_MODEL_c7ef59cc73014fbdb6b1dba7dfe1f604","tabbable":null,"tooltip":null,"value":"Done! Use &#x27;show&#x27; commands to display/save.   "}},"f74e24c0b5ed48ca94bd2f3aaafd8b6c":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HTMLStyleModel","state":{"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HTMLStyleModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"StyleView","background":null,"description_width":"","font_size":null,"text_color":null}},"f8313a80920e4f9991be71ac44ff1738":{"model_module":"@jupyter-widgets/controls","model_module_version":"2.0.0","model_name":"HTMLModel","state":{"_dom_classes":[],"_model_module":"@jupyter-widgets/controls","_model_module_version":"2.0.0","_model_name":"HTMLModel","_view_count":null,"_view_module":"@jupyter-widgets/controls","_view_module_version":"2.0.0","_view_name":"HTMLView","description":"","description_allow_html":false,"layout":"IPY_MODEL_83af913793cc4601bade5defb37f0e79","placeholder":"​","style":"IPY_MODEL_52ad0c39b5564249bb8a63b743a75e04","tabbable":null,"tooltip":null,"value":" [100%]   00:00 -&gt; (00:00 left)"}},"f99570e497694749aecea46fb29443d9":{"model_module":"@jupyter-widgets/base","model_module_version":"2.0.0","model_name":"LayoutModel","state":{"_model_module":"@jupyter-widgets/base","_model_module_version":"2.0.0","_model_name":"LayoutModel","_view_count":null,"_view_module":"@jupyter-widgets/base","_view_module_version":"2.0.0","_view_name":"LayoutView","align_content":null,"align_items":null,"align_self":null,"border_bottom":null,"border_left":null,"border_right":null,"border_top":null,"bottom":null,"display":"inline-flex","flex":null,"flex_flow":"row wrap","grid_area":null,"grid_auto_columns":null,"grid_auto_flow":null,"grid_auto_rows":null,"grid_column":null,"grid_gap":null,"grid_row":null,"grid_template_areas":null,"grid_template_columns":null,"grid_template_rows":null,"height":null,"justify_content":null,"justify_items":null,"left":null,"margin":null,"max_height":null,"max_width":null,"min_height":null,"min_width":null,"object_fit":null,"object_position":null,"order":null,"overflow":null,"padding":null,"right":null,"top":null,"visibility":null,"width":"100%"}}},"version_major":2,"version_minor":0}
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../data/data_access.html" class="pagination-link" aria-label="Data Access">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data Access</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../data/summarization.html" class="pagination-link" aria-label="Data Summarization">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Data Summarization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Foundations of Data Science by Oliver Schabenberger</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","selector":".lightbox","openEffect":"zoom","loop":false,"descPosition":"bottom"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>