<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Foundations of Data Science - 9&nbsp; SQL Basics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../data/integration.html" rel="next">
<link href="../data/visualization.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../data/sources_and_files.html">Part II. Data Preparation and Understanding</a></li><li class="breadcrumb-item"><a href="../data/sqlbasics.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">SQL Basics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Foundations of Data Science</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Part I. Data Science and Data Science Projects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../proj/history.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">History and Evolution of Data Science</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../proj/lifecycle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Data Science Project Lifecycle</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Part II. Data Preparation and Understanding</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/sources_and_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Sources and File Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/data_access.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Access</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Quality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/summarization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data Summarization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/sqlbasics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">SQL Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Integration</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Part III. Statistical Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statlearning/general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">General Topics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statlearning/mathstat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Probability and Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statlearning/linalg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Linear Algebra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statlearning/featproc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Feature and Target Processing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Part IV. Applied Ethics in Data Science</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ethics/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ethics/bias_harm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Bias and Harm in Algorithms</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ethics/privacy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Personal Information and Personal Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Part V. Integration of Data Science Solutions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/coding_practices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Coding Best Practices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../integ/tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Data Science Tools</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">9.1</span> Introduction</a></li>
  <li><a href="#types-of-sql-commands" id="toc-types-of-sql-commands" class="nav-link" data-scroll-target="#types-of-sql-commands"><span class="header-section-number">9.2</span> Types of SQL Commands</a></li>
  <li><a href="#most-common-sql-commands" id="toc-most-common-sql-commands" class="nav-link" data-scroll-target="#most-common-sql-commands"><span class="header-section-number">9.3</span> Most Common SQL Commands</a>
  <ul>
  <li><a href="#creating-and-modifying-a-table" id="toc-creating-and-modifying-a-table" class="nav-link" data-scroll-target="#creating-and-modifying-a-table">Creating and Modifying a Table</a></li>
  <li><a href="#pivoting-a-table" id="toc-pivoting-a-table" class="nav-link" data-scroll-target="#pivoting-a-table">Pivoting a Table</a></li>
  <li><a href="#dropping-a-table" id="toc-dropping-a-table" class="nav-link" data-scroll-target="#dropping-a-table">Dropping a Table</a></li>
  </ul></li>
  <li><a href="#select-statement" id="toc-select-statement" class="nav-link" data-scroll-target="#select-statement"><span class="header-section-number">9.4</span> SELECT Statement</a></li>
  <li><a href="#subqueries" id="toc-subqueries" class="nav-link" data-scroll-target="#subqueries"><span class="header-section-number">9.5</span> Subqueries</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../data/sources_and_files.html">Part II. Data Preparation and Understanding</a></li><li class="breadcrumb-item"><a href="../data/sqlbasics.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">SQL Basics</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-sql-basics" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">SQL Basics</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">9.1</span> Introduction</h2>
<p>SQL is a declarative programming language, you express through programming statements what you want to happen, not how to control the flow of the program. Other examples of declarative languages are CSS, HTML, XML, and Prolog. To support writing scripts, functions, and procedures, database vendors have added flow-control statements (if-then, loops, switches, etc.), but these are extensions of the database and not of the SQL language.</p>
<p>Is it pronounced “S-Q-L” or “sequel”? Both are acceptable but if you want to give a nod to its origin, then you would pronounce it ”sequel” like SEQUEL; the name given to the project by its inventors at IBM in the 1970s. The description as structured query language and the acronym SQL came later.</p>
<p>The concept of a <em>query</em> in SQL is very general: any interaction with a (relational) database. A query in the narrow sense asks questions about the data in the database or retrieves data. Commands that create tables, alter databases, update or delete records, and so on, are also considered queries.</p>
<p>SQL has been standardized and revised since 1986. SQL-92, for example, refers to the revision of the standard in 1992. However, SQL implementations are vendor-specific and do not necessarily comply with any standard. The SQL syntax between databases is similar enough that you can move your SQL code from one dialect to another without too much pain. Moving between databases you will find that the devil is not in the details of the SQL language, but in the details of how NULLs are represented, how date-time values are handled, how indexes work, how data are partitioned, whether foreign keys are supported, and so on. Since we use DuckDB in this chapter, we are following the DuckDB SQL syntax.</p>
<p>SQL can be difficult to master.</p>
<ul>
<li><p>Many programmers are more familiar and comfortable with imperative languages that specify the program flow step by step.</p></li>
<li><p>Declarative languages are domain specific, the domain for SQL is the manipulation of data in relational systems. This is associated with a lot of special terminology and domain-specific logic. The data scientist thinks in terms of rows and columns, the database engineer thinks in terms of predicates, projections, clauses, constraints, and relations.</p></li>
<li><p>While the number of relevant SQL commands is rather small, SQL queries can become astonishingly complex and unwieldy. A single SQL query that accesses multiple tables with correlated (dependent) subqueries, joins, and common table expressions can be hundreds of lines long. If you are not used to reading SQL, a simple subquery such as this one might give you a headache:</p></li>
</ul>
<pre class="{default}"><code>SELECT employee_number, name,
        (SELECT AVG(salary) 
           FROM employees
          WHERE department = emp.department) AS department_average
   FROM employees emp</code></pre>
<ul>
<li><p>The point of a declarative language is that the programmer specifies the desired result and leaves it to the particular implementation to achieve it. SQL novices often get frustrated because they know exactly <em>what</em> they want but not <em>how</em> to ask for it using SQL syntax.</p></li>
<li><p>Debugging SQL code is more difficult than debugging code in an imperative language. Error messages can be cryptic. A query that runs successfully is never wrong from the databases point of view, but it is wrong from the coder’s point of view if it does not produce the desired result.</p></li>
<li><p>A query that executes quickly for one database can run slowly in another database. It depends on database architecture, implementation, optimizations, etc. You must learn to ask for the right thing in the right way.</p></li>
</ul>
<p>An interesting aspect (quirk) of domain-specific logic in SQL is three-valued logic. In classical (boolean) logic, there are two logical values, TRUE and FALSE, expressing the relation of a proposition to the truth. In three-valued logic there is a third value, NULL, expressing an unknown state. NULL values are used in databases to represent absent entries and are akin to the concept of the missing value in analytics. NULL values are not zero or empty values. An empty string (“”) in a text column is a known value, a zero-byte string. A NULL value on the other hand states that a string is absent.</p>
<p>The examples that follow in this section use DuckDB with the <code>ads5064.ddb</code> database from the command line as follows:</p>
<pre class="{default}"><code>&gt; duckdb ads5064.ddb
D</code></pre>
<p>Because NULL is a logical state, SQL defines operations on NULL values. Suppose A is TRUE, B is FALSE, and C is NULL, then A or B and A or C both evaluate to TRUE, but A and B is FALSE whereas A and C is also NULL (unknown). To achieve “expected” results when operating on NULL values, special syntax is needed. For example,</p>
<pre class="{default}"><code>SELECT * FROM landsales WHERE improve = NULL;

┌───────┬─────────┬───────┬───────┬───────────┐
│ land  │ improve │ total │ sale  │ appraisal │
│ int64 │  int64  │ int64 │ int64 │  double   │
├─────────────────────────────────────────────┤
│                   0 rows                    │
└─────────────────────────────────────────────┘</code></pre>
<p>returns no rows since the comparison <code>x = NULL</code> is never TRUE, its result is always unknown (NULL). If you use this syntax to check for missing values in your data you will conclude that there are none.</p>
<p>The correct query uses syntax designed to operate with NULL values:</p>
<pre class="{default}"><code>SELECT * FROM landsales WHERE improve IS NULL;
┌───────┬─────────┬───────┬────────┬───────────┐
│ land  │ improve │ total │  sale  │ appraisal │
│ int64 │  int64  │ int64 │ int64  │  double   │
├───────┼─────────┼───────┼────────┼───────────┤
│ 42394 │         │       │ 168000 │           │
│ 93200 │         │       │ 422000 │           │
│ 65376 │         │       │ 286500 │           │
│ 42400 │         │       │        │           │
└───────┴─────────┴───────┴────────┴───────────┘

SELECT count(*) FROM landsales WHERE improve IS NULL;
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│            4 │
└──────────────┘ 
</code></pre>
</section>
<section id="types-of-sql-commands" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="types-of-sql-commands"><span class="header-section-number">9.2</span> Types of SQL Commands</h2>
<p>SQL commands are arranged in logical groups. The most important group for the data scientist is the Data Manipulation Language (DML) group, it consists of statements that change the data stored within a database table and traditionally also includes the most important SQL statement, SELECT. The second most important group of SQL commands is the Data Definition Language (DDL), it provides syntax to create and modify database objects.</p>
<ul>
<li><p><strong>Data Definition Language</strong> (DDL): syntax to create and modify database objects. The commands are about the objects themselves, not the data they contain. For example, the CREATE TABLE statement defines the schema of a table and creates it, but it does not populate the table with data. Commands in this group include CREATE, DROP, ALTER.</p></li>
<li><p><strong>Data Manipulation Language</strong> (DML): syntax to query and modify the contents of tables. The most important SQL command in this group is SELECT. Other commands in this group are INSERT, UPDATE, DELETE. The SELECT statement is sometimes pulled into a separate group, the Data Querying Language (DQL). Since it would be the only statement in that group and because SELECT INTO also modifies rows in a table, the SELECT statement is often included as part of the DML.</p></li>
<li><p><strong>Data Control Language</strong> (DCL): to control access and manage permissions for users of the database. Commands such as GRANT, DENY, and REVOKE are part of the DCL. As a data scientist you are unlikely to work with DCL commands, they are the domain of the database administrator (DBA). However, you might be charged with setting up and maintaining a database and DCL will help you to change what users (or roles) are allowed to do in the database. The following statements allow <code>user1</code> to run a SELECT statement on <code>table_foo</code> but disallows updates to the table.</p></li>
</ul>
<pre class="{default}"><code>GRANT SELECT ON table_foo TO user1;
DENY UPDATE ON table_foo TO user1;
</code></pre>
<p>Not all databases support DCL. SQLite and DuckDB do not.</p>
</section>
<section id="most-common-sql-commands" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="most-common-sql-commands"><span class="header-section-number">9.3</span> Most Common SQL Commands</h2>
<p>The most important SQL commands for a data scientist are the following:</p>
<ul>
<li><p>CREATE TABLE</p></li>
<li><p>ALTER TABLE</p></li>
<li><p>DROP TABLE</p></li>
<li><p>SELECT</p></li>
<li><p>INSERT INTO</p></li>
<li><p>UPDATE</p></li>
<li><p>DELETE FROM</p></li>
</ul>
<section id="creating-and-modifying-a-table" class="level3">
<h3 class="anchored" data-anchor-id="creating-and-modifying-a-table">Creating and Modifying a Table</h3>
<p>We demonstrate these with a small example using DuckDB. You can find the complete documentation for SQL in DuckDB <a href="https://duckdb.org/docs/sql/introduction">here</a>. A separate section then dives into the SELECT statement, the workhorse for data analysis in relational DBMS.</p>
<p>First, let’s create a small table with information on some cities around the world.</p>
<pre class="{default}"><code>CREATE TABLE Cities (Country VARCHAR, Name VARCHAR, Year INT, Population INT);</code></pre>
<p>The table has four columns named <code>Country</code>, <code>Name</code>, <code>Year</code>, and <code>Population</code>, respectively. The first two are of type VARCHAR (allowing character strings of variable length), the last two are of type INT.</p>
<p>If we were to issue the CREATE TABLE statement again, the database would throw an error because the Cities table now exists. To replace an existing table, use CREATE OR REPLACE TABLE:</p>
<pre class="{default}"><code>CREATE OR REPLACE TABLE Cities (Country    VARCHAR, 
                                Name       VARCHAR, 
                                Year       INT, 
                                Population INT);
</code></pre>
<p>A very useful feature is the addition of check constraints. Suppose you want to make sure that only data after the year 2000 are entered for the <code>Year</code> column. You can add a check constraint like this:</p>
<pre class="{default}"><code>CREATE OR REPLACE TABLE Cities (Country    VARCHAR, 
                                Name       VARCHAR, 
                                Year       INT CHECK (Year &gt;= 2000), 
                                Population INT);
</code></pre>
<p>Trying to insert a record that fails the check will result in an error:</p>
<pre class="{default}"><code>INSERT INTO Cities VALUES ('NL', 'Amsterdam', 1999, 1005);

Error: Constraint Error: CHECK constraint failed: Cities</code></pre>
<p>Once the table exists in the catalog, we can use the ALTER TABLE statement to change its structure, for example, by renaming, adding, or removing columns, changing data types or defaults.</p>
<pre class="{default}"><code>ALTER TABLE Cities RENAME Name to CityName;
ALTER TABLE Cities ADD Column k INTEGER;
ALTER TABLE Cities RENAME to WorldCities;
</code></pre>
<p>The first statement renames the Name column to <code>CityName</code>, the second statement adds an integer column named k, and the third statement renames the table.</p>
<p>To populate the table with data, we insert rows. The following statements add one row at a time and then retrieves the entire contents of the table:</p>
<pre class="{default}"><code>INSERT INTO WorldCities VALUES ('NL', 'Amsterdam', 2000, 1005, 1);
INSERT INTO WorldCities VALUES ('NL', 'Amsterdam', 2010, 1065, 3);
INSERT INTO WorldCities VALUES ('NL', 'Amsterdam', 2020, 1158, 4);
INSERT INTO WorldCities VALUES ('US', 'Seattle', 2000, 564, 5432);
INSERT INTO WorldCities VALUES ('US', 'Seattle', 2010, 608, 46);
INSERT INTO WorldCities VALUES ('US', 'Seattle', 2020, 738, 986);
INSERT INTO WorldCities VALUES ('US', 'New York City', 2000, 8015, 0);
INSERT INTO WorldCities VALUES ('US', 'New York City', 2010, 8175, 987);
INSERT INTO WorldCities VALUES ('US', 'New York City', 2020, 8772, 23);

SELECT * FROM WorldCities;

┌─────────┬───────────────┬───────┬────────────┬───────┐
│ Country │   CityName    │ Year  │ Population │   k   │
│ varchar │    varchar    │ int32 │   int32    │ int32 │
├─────────┼───────────────┼───────┼────────────┼───────┤
│ NL      │ Amsterdam     │  2000 │       1005 │     1 │
│ NL      │ Amsterdam     │  2010 │       1065 │     3 │
│ NL      │ Amsterdam     │  2020 │       1158 │     4 │
│ US      │ Seattle       │  2000 │        564 │  5432 │
│ US      │ Seattle       │  2010 │        608 │    46 │
│ US      │ Seattle       │  2020 │        738 │   986 │
│ US      │ New York City │  2000 │       8015 │     0 │
│ US      │ New York City │  2010 │       8175 │   987 │
│ US      │ New York City │  2020 │       8772 │    23 │
└─────────┴───────────────┴───────┴────────────┴───────┘ 
</code></pre>
<p>We won’t need the column k anymore, so we can drop it with</p>
<pre class="{default}"><code>ALTER TABLE WorldCities DROP COLUMN k;</code></pre>
</section>
<section id="pivoting-a-table" class="level3">
<h3 class="anchored" data-anchor-id="pivoting-a-table">Pivoting a Table</h3>
<p>A pivot table is a summary for data that contains categorical variables. If the aggregation is a simple count, the pivot table is also called a contingency table. These tables are useful to summarize data by categories and to see trends. DuckDB implements the SQL PIVOT statement; the basic syntax is</p>
<pre class="{default}"><code>PIVOT ⟨dataset⟩ 
  ON ⟨columns⟩
  USING ⟨values⟩ 
  GROUP BY ⟨rows⟩  
  ORDER BY ⟨columns_with_order_directions⟩
  LIMIT ⟨number_of_rows⟩;
</code></pre>
<p>The ON clause lists the columns on which to pivot the table. In the <code>WorldCities</code> example we might want to pivot on <code>Year</code> to retrieve the average population for each year:</p>
<pre class="{default}"><code> PIVOT WorldCities on YEAR USING mean(population);

┌─────────┬───────────────┬────────┬────────┬────────┐
│ Country │   CityName    │  2000  │  2010  │  2020  │
│ varchar │    varchar    │ double │ double │ double │
├─────────┼───────────────┼────────┼────────┼────────┤
│ US      │ New York City │ 8015.0 │ 8175.0 │ 8772.0 │
│ NL      │ Amsterdam     │ 1005.0 │ 1065.0 │ 1158.0 │
│ US      │ Seattle       │  564.0 │  608.0 │  738.0 │
└─────────┴───────────────┴────────┴────────┴────────┘ 
</code></pre>
<p>The USING clause determines how to aggregate the values that are split into columns. If it is not provided, the PIVOT statement defaults to <code>count(*)</code> aggregation.</p>
<p>The GROUP BY clause allows you to further aggregate the results and the ORDER BY statement affects how the output is displayed:</p>
<pre class="{default}"><code>PIVOT WorldCities on YEAR
      USING mean(population) 
      GROUP BY Country 
      ORDER BY Country DESC;

┌─────────┬────────┬────────┬────────┐
│ Country │  2000  │  2010  │  2020  │
│ varchar │ double │ double │ double │
├─────────┼────────┼────────┼────────┤
│ US      │ 4289.5 │ 4391.5 │ 4755.0 │
│ NL      │ 1005.0 │ 1065.0 │ 1158.0 │
└─────────┴────────┴────────┴────────┘ 
</code></pre>
<p>To obtain multiple aggregations, provide a list in the USING clause:</p>
<pre class="{default}"><code>PIVOT WorldCities on YEAR
      USING mean(population) as mn,
            max(population) as mx
      GROUP BY Country 
      ORDER BY Country DESC;

┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ Country │ 2000_mn │ 2000_mx │ 2010_mn │ 2010_mx │ 2020_mn │ 2020_mx │
│ varchar │ double  │  int32  │ double  │  int32  │ double  │  int32  │
├─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ US      │  4289.5 │    8015 │  4391.5 │    8175 │  4755.0 │    8772 │
│ NL      │  1005.0 │    1005 │  1065.0 │    1065 │  1158.0 │    1158 │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘ 
</code></pre>
<p>You might want to combine creation of a table and populating it with data into a single step. For example, you might want to create a database table from the contents of a CSV file. That is accomplished by adding an AS SELECT clause to the CREATE TABLE statement:</p>
<pre class="{default}"><code>CREATE OR REPLACE TABLE iris AS SELECT * FROM "../datasets/iris.csv”;</code></pre>
<p>You can use just FROM as a shorthand for SELECT * FROM:</p>
<pre class="{default}"><code>CREATE OR REPLACE TABLE iris AS FROM "../dataswts/iris.csv”;</code></pre>
<p>This shorthand works in general in DuckDB:</p>
<pre class="{default}"><code>FROM WorldCities WHERE Country='NL';

┌─────────┬───────────┬───────┬────────────┐
│ Country │ CityName  │ Year  │ Population │
│ varchar │  varchar  │ int32 │   int32    │
├─────────┼───────────┼───────┼────────────┤
│ NL      │ Amsterdam │  2000 │       1005 │
│ NL      │ Amsterdam │  2010 │       1065 │
│ NL      │ Amsterdam │  2020 │       1158 │
└─────────┴───────────┴───────┴────────────┘ 
</code></pre>
<p>If you want to create a temporary table that resides in memory and is automatically dropped when the connection to DuckDB is closed, use CREATE TEMP TABLE:</p>
<pre class="{default}"><code>CREATE TEMP TABLE foo AS FROM "../datasets/iris.csv";</code></pre>
</section>
<section id="dropping-a-table" class="level3">
<h3 class="anchored" data-anchor-id="dropping-a-table">Dropping a Table</h3>
<p>Finally, when the table is no longer needed, we can remove it from the catalog with DROP TABLE:</p>
<pre class="{default}"><code>DROP TABLE WorldCities;</code></pre>
</section>
</section>
<section id="select-statement" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="select-statement"><span class="header-section-number">9.4</span> SELECT Statement</h2>
<p>The SELECT statement is the workhorse for querying, analyzing, combining, and ordering data in database tables. The more important basic syntax elements of SELECT are</p>
<pre class="{default}"><code>SELECT select_list
   FROM tables
   WHERE condition
   GROUP BY groups
   HAVING group_filter
   ORDER BY order_expr
   LIMIT n;
</code></pre>
<p>The logical start of the SELECT query is the FROM clause where you specify the data source for the query. The <code>select_list</code> prior to the FROM clause specifies the columns in the result set of the query. This can be columns from results in the FROM clause, aggregations, and combinations. If you want to specifically name element of the <code>select_list</code>, you can assign an alias with the AS clause, as in this example:</p>
<pre class="{default}"><code>SELECT sepal_length AS SL, sepal_width AS SW from iris LIMIT 5;

┌────────┬────────┐
│   SL   │   SW   │
│ double │ double │
├────────┼────────┤
│    5.1 │    3.5 │
│    4.9 │    3.0 │
│    4.7 │    3.2 │
│    4.6 │    3.1 │
│    5.0 │    3.6 │
├────────┴────────┤
│     5 rows      │
└─────────────────┘ 
</code></pre>
<p>To include everything in the FROM clause into the <code>select_list</code>, use the asterisk wildcard (star notation):</p>
<pre class="{default}"><code>SELECT * FROM iris LIMIT 4;

┌──────────────┬─────────────┬──────────────┬─────────────┬─────────┐
│ sepal_length │ sepal_width │ petal_length │ petal_width │ species │
│    double    │   double    │    double    │   double    │ varchar │
├──────────────┼─────────────┼──────────────┼─────────────┼─────────┤
│          5.1 │         3.5 │          1.4 │         0.2 │ setosa  │
│          4.9 │         3.0 │          1.4 │         0.2 │ setosa  │
│          4.7 │         3.2 │          1.3 │         0.2 │ setosa  │
│          4.6 │         3.1 │          1.5 │         0.2 │ setosa  │
└──────────────┴─────────────┴──────────────┴─────────────┴─────────┘ 
</code></pre>
<p>SELECT queries can quickly get complicated because the FROM clause can contain a single table, multiple tables that are joined together, or another SELECT query (this is called a subquery):</p>
<pre class="{default}"><code>SELECT land, improve, 
       (SELECT avg(sale) FROM landsales as average) 
FROM (SELECT * from landsales where total &gt; 100000);

┌────────┬─────────┬──────────────────────────────────────────────┐
│  land  │ improve │ (SELECT avg(sale) FROM landsales AS average) │
│ int64  │  int64  │                   double                     │
├────────┼─────────┼──────────────────────────────────────────────┤
│  45990 │   91402 │                           217445.45454545456 │
│  56658 │  153806 │                           217445.45454545456 │
│  51428 │   72451 │                           217445.45454545456 │
│  76125 │   78172 │                           217445.45454545456 │
│ 154360 │   61934 │                           217445.45454545456 │
│  40800 │   92606 │                           217445.45454545456 │
└────────┴─────────┴──────────────────────────────────────────────┘ 
</code></pre>
<p>In the previous SQL code, the <code>select_list</code> contains a SELECT statement that returns the average sale price for all land sales. The FROM clause contains another SELECT statement with a WHERE clause. The result set consists of the land and improvement value for sales where the total value exceeded 100,000 and the average sale for all properties (including the ones with total value below 100,000).</p>
<p>The WHERE clause in the SELECT applies filters to the data. Only rows that match the WHERE clause are processed.</p>
<pre class="{default}"><code>SELECT * FROM iris WHERE species LIKE '%osa' LIMIT 10;
Output
┌──────────────┬─────────────┬──────────────┬─────────────┬─────────┐
│ sepal_length │ sepal_width │ petal_length │ petal_width │ species │
│    double    │   double    │    double    │   double    │ varchar │
├──────────────┼─────────────┼──────────────┼─────────────┼─────────┤
│          5.1 │         3.5 │          1.4 │         0.2 │ setosa  │
│          4.9 │         3.0 │          1.4 │         0.2 │ setosa  │
│          4.7 │         3.2 │          1.3 │         0.2 │ setosa  │
│          4.6 │         3.1 │          1.5 │         0.2 │ setosa  │
│          5.0 │         3.6 │          1.4 │         0.2 │ setosa  │
│          5.4 │         3.9 │          1.7 │         0.4 │ setosa  │
│          4.6 │         3.4 │          1.4 │         0.3 │ setosa  │
│          5.0 │         3.4 │          1.5 │         0.2 │ setosa  │
│          4.4 │         2.9 │          1.4 │         0.2 │ setosa  │
│          4.9 │         3.1 │          1.5 │         0.1 │ setosa  │
├──────────────┴─────────────┴──────────────┴─────────────┴─────────┤
│ 10 rows                                                 5 columns │
└───────────────────────────────────────────────────────────────────┘ 
</code></pre>
<p>The GROUP BY clause specifies the groupings for aggregations.</p>
<pre class="{default}"><code>SELECT count(*), max(sepal_length) FROM iris GROUP BY species;

┌──────────────┬───────────────────┐
│ count_star() │ max(sepal_length) │
│    int64     │      double       │
├──────────────┼───────────────────┤
│           50 │               7.9 │
│           50 │               5.8 │
│           50 │               7.0 │
└──────────────┴───────────────────┘ 
</code></pre>
<p>You can specify multiple columns in the grouping or use the GROUP BY ALL shorthand. The following are equivalent:</p>
<pre class="{default}"><code>SELECT League, Division, mean(RBI) FROM Hitters GROUP BY League, Division;
SELECT League, Division, mean(RBI) FROM Hitters GROUP BY ALL;

┌─────────┬──────────┬───────────────────┐
│ League  │ Division │     mean(RBI)     │
│ varchar │ varchar  │      double       │
├─────────┼──────────┼───────────────────┤
│ A       │ E        │ 54.37647058823529 │
│ A       │ W        │ 48.81111111111111 │
│ N       │ E        │ 44.94444444444444 │
│ N       │ W        │ 42.85333333333333 │
└─────────┴──────────┴───────────────────┘
</code></pre>
<p>The HAVING clause in the SELECT statement causes confusion sometimes, but it is fairly easy to understand as a filter that is applied <strong>after</strong> the GROUP BY clause. The WHERE clause on the other hand is a filter applied <strong>before</strong> the GROUP BY clause. In other words, the WHERE clause selects which rows participate in the GROUP BY operation. The HAVING clause determines which result of the GROUP BY operation are filtered.</p>
<pre class="{default}"><code>SELECT League, Division, 
       count(*) as count, 
       avg(RBI) AS average 
FROM Hitters 
GROUP BY ALL
HAVING count &gt; 80;

┌─────────┬──────────┬───────┬───────────────────┐
│ League  │ Division │ count │      average      │
│ varchar │ varchar  │ int64 │      double       │
├─────────┼──────────┼───────┼───────────────────┤
│ A       │ E        │    85 │ 54.37647058823529 │
│ A       │ W        │    90 │ 48.81111111111111 │
└─────────┴──────────┴───────┴───────────────────┘ 
</code></pre>
<p>Without the HAVING clause, the SELECT statement would return results on two additional groupings:</p>
<pre class="{default}"><code>SELECT League, Division, 
       count(*) as count, 
       avg(RBI) AS average 
FROM Hitters 
GROUP BY ALL;

┌─────────┬──────────┬───────┬───────────────────┐
│ League  │ Division │ count │      average      │
│ varchar │ varchar  │ int64 │      double       │
├─────────┼──────────┼───────┼───────────────────┤
│ A       │ E        │    85 │ 54.37647058823529 │
│ A       │ W        │    90 │ 48.81111111111111 │
│ N       │ E        │    72 │ 44.94444444444444 │
│ N       │ W        │    75 │ 42.85333333333333 │
└─────────┴──────────┴───────┴───────────────────┘  
</code></pre>
<p>The ORDER BY and LIMIT clause also operate on the result set of the query. LIMIT is applied at the end of the query and returns only a specified number of rows in the result set. The ORDER BY clause affects how the rows of the result set are arranged. LIMIT without an ORDER BY can be non-deterministic, multiple runs can produce different results depending on the parallel processing of the data. However, combining ORDER BY and LIMIT generates reproducible results and is a common technique to fetch the top or bottom rows. The following SELECT statement retrieves statistics for the baseball players with the five highest RBI values:</p>
<pre class="{default}"><code>SELECT AtBat, Hits, HmRun, Runs, RBI, Walks, Errors 
   FROM Hitters ORDER BY RBI DESC LIMIT 5;

┌───────┬───────┬───────┬───────┬───────┬───────┬────────┐
│ AtBat │ Hits  │ HmRun │ Runs  │  RBI  │ Walks │ Errors │
│ int64 │ int64 │ int64 │ int64 │ int64 │ int64 │ int64  │
├───────┼───────┼───────┼───────┼───────┼───────┼────────┤
│   663 │   200 │    29 │   108 │   121 │    32 │      6 │
│   600 │   144 │    33 │    85 │   117 │    65 │     14 │
│   637 │   174 │    31 │    89 │   116 │    56 │      9 │
│   677 │   238 │    31 │   117 │   113 │    53 │      6 │
│   618 │   200 │    20 │    98 │   110 │    62 │      8 │
└───────┴───────┴───────┴───────┴───────┴───────┴────────┘ 
</code></pre>
</section>
<section id="subqueries" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="subqueries"><span class="header-section-number">9.5</span> Subqueries</h2>
<p>A subquery is a query inside another query. The subquery is also called the inner query and the query containing it is referred to as the outer query. Subqueries are said to be <strong>uncorrelated</strong> if they are self-contained and can be run without the outer query. For example, the following SQL statement contains an uncorrelated subquery, <code>select min(weight) from auto</code>, which you can run as a stand-alone query</p>
<pre class="{default}"><code>select name from auto where weight = (select min(weight) from auto);

┌─────────────┐
│    name     │
│   varchar   │
├─────────────┤
│ datsun 1200 │
└─────────────┘ 
</code></pre>
<p>The outer query in this example is <code>SELECT name FROM auto WHERE weight =</code>.</p>
<p>You can use subqueries together with SELECT EXISTS to test for the existence of rows in the subquery:</p>
<pre class="{default}"><code>select exists(select * from auto where horsepower &gt; 300);

┌─────────────────────────────────────────────────────┐
│ EXISTS(SELECT * FROM auto WHERE (horsepower &gt; 300)) │
│                       boolean                       │
├─────────────────────────────────────────────────────┤
│ false                                               │
└─────────────────────────────────────────────────────┘
</code></pre>
<p>A subquery is said to be <strong>correlated</strong> if the subquery uses values from the outer query. You can think of the subquery as a function that is run for every row in the data. Suppose we want to find the minimum reaction time for each subject in the sleep table. The data represent reaction times for 18 subjects measured on ten days of a sleep deprivation study.</p>
<pre class="{default}"><code>SELECT *
  FROM sleep AS s
  WHERE Reaction =
      (SELECT MIN(Reaction)
       FROM sleep
       WHERE sleep.Subject=s.Subject);

┌──────────┬───────┬─────────┐
│ Reaction │ Days  │ Subject │
│  double  │ int64 │  int64  │
├──────────┼───────┼─────────┤
│   249.56 │     0 │     308 │
│ 202.9778 │     2 │     309 │
│ 194.3322 │     1 │     310 │
│ 280.2396 │     6 │     330 │
│    285.0 │     1 │     331 │
│ 234.8606 │     0 │     332 │
│ 276.7693 │     2 │     333 │
│ 243.3647 │     2 │     334 │
│  235.311 │     7 │     335 │
│ 291.6112 │     2 │     337 │
│ 230.3167 │     1 │     349 │
│ 243.4543 │     1 │     350 │
│ 250.5265 │     0 │     351 │
│ 221.6771 │     0 │     352 │
│ 257.2424 │     2 │     369 │
│  225.264 │     0 │     370 │
│ 259.2658 │     6 │     371 │
│ 269.4117 │     0 │     372 │
├──────────┴───────┴─────────┤
│ 18 rows          3 columns │
└────────────────────────────┘ 
</code></pre>
<p>Subject 308 has the smallest reaction time on day 0 of the study, subject 309 has the smallest reaction time at day 2, and so forth. The subquery is correlated, because it uses the column <code>s.Subject</code> from the outer query.</p>
<p>We could have achieved the same aggregation of smallest reaction time by subject with a simple query with GROUP BY clause:</p>
<pre class="{default}"><code>select min(Reaction), Subject from sleep group by subject limit 5;

┌───────────────┬─────────┐
│ min(Reaction) │ Subject │
│    double     │  int64  │
├───────────────┼─────────┤
│        249.56 │     308 │
│      202.9778 │     309 │
│      194.3322 │     310 │
│      280.2396 │     330 │
│         285.0 │     331 │
└─────────────────────────┘ 
</code></pre>
<p>The difference is that the correlated subquery returns actual records from the table whereas the SELECT with GROUP BY clause returns the result of aggregation. Put it another way: do you want to see the min reaction time for each subject or do you want to see the records that match the min reaction time for each subject?</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../data/visualization.html" class="pagination-link" aria-label="Data Visualization">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Data Visualization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../data/integration.html" class="pagination-link" aria-label="Data Integration">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Integration</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Foundations of Data Science by Oliver Schabenberger</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>